### ISSUE TITLE
Specify path of eslint executable

### ISSUE THREAD

**Issue by LiteracyFanatic** [microsoft/vscode-eslint#1028]
In some cases I like to use `eslint` on one-off scripts that aren't part of a proper project. In other words, there is a single file that I run with with `node` and I don't use `npm` to install any tooling into a `node_modules/` folder. I understand that I can use `npm install --global eslint`, but I prefer to install command line tools using my operating system's package manager whenever possible. Right now, there doesn't seem to be any way to point this extension to the actual location of the executable. I know there is `eslint.nodePath`, but  there doesn't seem to be any way to point this extension to the actual location of the executable  like `/usr/bin/eslint` unless I am missing something.

**Comment by dbaeumer** [comment]
Pointing to a executable is not possible since the extension doesn't run an executable. It loads the ESLint npm library and uses the CLIEngine API. So `eslint.nodePath` will allow you to point to a custom install location to load the node npm module. 

I will close the issue. Please ping if you think there is still something the extension should do.

**Comment by LiteracyFanatic** [comment]
That makes sense. Thanks for the reply.
