### ISSUE TITLE
Trust this eslint version asked every time

### ISSUE THREAD

**Issue by tapz** [microsoft/vscode-eslint#1034]
Every time I start VSCode each window asks this question. Every time I answer yes, but the extension asks this again next time I start VSCode. Can't you add Always allow button?

<img width="466" alt="Screenshot 2020-07-30 at 13 00 23" src="https://user-images.githubusercontent.com/11726387/88910487-3753f380-d265-11ea-8754-5da26bcd3b5b.png">

**Comment by dbaeumer** [comment]
@tapz this shouldn't happen and actually doesn't happen for me. Would you be able to give me access to your workspace (e.g. as a GitHub repository) so that I can investigate why this is happening for you?

Is there anything special when you start VS Code. Are you using the `--user-data-dir` option?

**Comment by tapz** [comment]
This happens with all of my 5 workspaces. Sorry, the projects are not my personal, so I cannot give access to the repos.

I'm not using --user-data-dir option.

**Comment by dbaeumer** [comment]
@tapz just to clarify. You get ask once per workspace right. This is expected since every workspace usually has its own version of ESLint. 

I talked to the VS Code team about this as well and they will start to work on a trusted workspace model which will allow the ESLint extension to remove the dialog again. The team recognized that the approach of every feature doing the checks is not scaling.

**Comment by tapz** [comment]
Thanks @dbaeumer !

**Comment by dbaeumer** [comment]
Will treat it as a dup of 1012 then
