### ISSUE TITLE
Please manage the release process with a little more professionalism

### ISSUE THREAD

**Issue by wyuenho** [microsoft/vscode-eslint#1037]
Extension is pushed to VS code before tagging or even available on npm, or sometimes the exact reverse, commit messages are full of noise, change log not kept up to date, server breaks all the time due to silly mistakes such as requesting non-existent methods due to spelling errors and introducing out-of-spec LSP methods all over the place, causing problems with downstream users not on VS code.

This isn't your side project you do for fun, 1000s of people depend on it every day, and it's published under Microsoft. Please show a little discipline in your craft.

**Comment by dbaeumer** [comment]
This extension is has its name says special for VS Code and its marketplace and the server is currently not meant to work outside of VS Code and therefore NOT published to npm. There is a separate issue https://github.com/microsoft/vscode-eslint/issues/1003 that requests a server that can be used using npm install and either only depends on LSP methods or clearly documents what additional methods a client needs to implement (which is according to LSP allowed).

And I do think that the change log nicely documents the changes that happened https://github.com/microsoft/vscode-eslint/blob/release/2.1.x/CHANGELOG.md. 

The only thing I agree on is that the history already contains a 2.1.9 tag although it is not published yet in the Marketplace. I will remove the tag again to make this more clear. This happened since I am still waiting for possible additional stuff going into 2.1.9

I will close the issue. If you want to contribute to a server that is usuable outside of VS Code please contribute to #1003

**Comment by wyuenho** [comment]
The problem, is not merely whether you have an npm package or not, but that fact you care little of the user experience of your end product, therefore you don't test with different project setups, don't care for describing the rationale for changes in the commit message, and don't even care for maintaining good a publishing process. 2.1.8 was published before even merging to master, and issues like #1012 is just silly. There is no way to no know how much of a hassle it will be if you do the minimal amount dogfooding. None of these problems are isolated incidents. I implore you to manage this project a little better. You have the luxury of getting paid for doing open source, many people don't have this luxury and do a better job than this.

**Comment by dbaeumer** [comment]
We always self host on the extension before I publish it. 2.1.8 was a big exception in the release process since it was a security release and the code could not show up in public before it got released to the marketplace. In the meantime the code got correctly merged into the open source repository (into the release branch and master). In ALL other cases the code was always available in the repository when published

Feel free to contribute if you have idea to further improve this.

**Comment by wyuenho** [comment]
Are you telling me [all of this](https://github.com/microsoft/vscode-eslint/compare/master...release/2.1.8) has to do with a security fix? How many silly spelling errors to interfaces have you made in the code base? Where's the tag for 1.9.2? Where's the Changelog between 2.0.5 and 2.0.9?

**Comment by dbaeumer** [comment]
Yes, this was all due to the security fix.  There is still a difference between 2.1.8 and master since the security fix was made on a branch and no new release as been made off master. It could be that same older version don't have proper tags. If I recall the version 2.0.6 - 2.0.8 correctly then these were some internal testing version provided as insider version for special testing. 

As said earlier feel free to contribute if you have ideas how to improve this further.

**Comment by wyuenho** [comment]
Does your code get reviewed before merging or is this entirely a one-man project?
