### ISSUE TITLE
Limit underline for large reported nodes

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode-eslint#1057]
Some ESLint rules highlight large nodes. This causes large code blocks to get reported in the editor. This is a bad UX, as this makes it hard to see other issues in the file.

In a discussion in jest-community/eslint-plugin-jest#539, jest-community/eslint-plugin-jest#641, and jest-community/eslint-plugin-jest#654, a collaborator stated this should be solved by the editor plugins, not the plugins.

The issue isn’t limited to one rule. For example [filenames/match-regex](https://github.com/selaux/eslint-plugin-filenames/blob/master/lib/rules/match-regex.js) reports the `Program` node.

I can’t think of a proper solution myself. Perhaps the number of lines highlighted by a single ESLint report can be limited.

**Comment by dbaeumer** [comment]
I intentionally stayed away from modifying the ranges reported by ESLint in any ways since I have no knowledge about the actual rendering of the error (for example is the file open?). So I would suggest that something like this is implemented in the UI itself (e.g. VS Code).

I am leaning towards closing the issue.
