### ISSUE TITLE
"No ESLint configuration found." message keeps reappearing

### ISSUE THREAD

**Issue by oheard** [Microsoft/vscode-eslint#107]
After dismissing the above message it keeps reappearing every few seconds.

**Comment by book010** [comment]
This message is also annoying whenever I open diff view with js 

![2016-08-03 1 18 04](https://cloud.githubusercontent.com/assets/667219/17354694/9bc2bd84-597d-11e6-946f-6c076daa3c59.png)

**Comment by hmmChase** [comment]
If you make an .eslintrc.json file like this:

![image](https://cloud.githubusercontent.com/assets/10532835/17384013/17e57040-59a7-11e6-8de5-6d545e883e51.png)

that message won't pop up

**Comment by seansean11** [comment]
I understand that eslint needs some configuration to lint files, but the appearance of the error on every save and edit is covering up my file name tabs at the top of the app.  Sometimes I just want to jump into a project that isn't using eslint and make a change.  Instead of having to create a blank configuration file and adding that to my .gitignore, I ended up turning off the plugin.  I think that one error message when opening a project would be sufficient.

**Comment by Mirodil** [comment]
I have the same issue. I think this extension should use default configuration with specified in the vscode `Default Settings` and `User Settings` as we have following:
```json
   // ESLint configuration

    // Control whether eslint is enabled for JavaScript files or not.
    "eslint.enable": true,

    // The eslint options object to provide args to the eslint command.
    "eslint.options": {},

```

**Comment by jamietre** [comment]
Ideally, this error would never appear. If there's no eslint config, then presumably, my project is not using eslint. So just don't do anything for this project. I don't want to have to create a dummy config every time I use vscode to work on some legacy project.

**Comment by jdforsythe** [comment]
There's two scenarios that are both better than the constant nagging notification:

1. Default to the "standard" config if no eslintrc or config options are set.
2. Default to not linting at all if there is no configuration.

I'd vote for the first choice, although it could be another configuration option that just defaults to the first.

**Comment by jamietre** [comment]
A config option would be the fine, but in the absence of that I'd definitely prefer it just do nothing. For example people might conceivably want to have both an eslint and a jshint extension installed, and whichever one is applicable given the presence of an appropriate config would engage for that project.

**Comment by CrabDude** [comment]
I believe generally [`SublimeLinter-contrib-eslint`](https://github.com/roadhump/SublimeLinter-eslint) et. al behave as such:

1. Use the local project eslint config (e.g., `<project_root>/.eslintrc`)
2. Otherwise, use the global eslint config (e.g., `~/.eslintrc`)
3. Otherwise, don't eslint.

@roadhump Would you be willing to confirm?

**Comment by steveinatorx** [comment]
@CrabDude i would be willing to take a crack at this PR if @roadhump agrees to this convention.  Another nice idea here would be to allow a workspace override setting for the .eslintrc location in case you have submodule paths.

**Comment by CrabDude** [comment]
@steveinatorx Sorry for the confusion. I believe @dbaeumer is [one of] the primary maintainers of `vscode-eslint`. @roadhump is the maintainer of [`SublimeLinter-contrib-eslint`](https://github.com/roadhump/SublimeLinter-eslint), whom I mentioned just to confirm the `SublimeLinter-eslint` approach.

**Comment by steveinatorx** [comment]
np

**Comment by roadhump** [comment]
@CrabDude It seems that `SublimeLinter-contrib-eslint` crashes the same way. It's a `ESLint v3` change to always require a config, as I know. I think the best way is just not to show this specific error to editor's user.

**Comment by steveinatorx** [comment]
silent fail? do you think a better use case is a hybrid of @crabdude suggestion with this order of precedence:

1. look for a workspace specific config setting
2. search in project root
3. search in user ~

linting IMHO often requires a project specific granularity so a one size fits all might not be the best approach... just my unsolicited $0.02

**Comment by dbaeumer** [comment]
To make this a more pleasant experience I implemented the following for now:

- the error is only shown once during one session. 
- if you later on add a config file it will automatically be picked up. No need for config.

I stayed away from having default options since then I need to indicate which options are used. Currently the extension follows the eslint rules.

We are working on API for VSCode to control settings from the extension. As soon as this is in I will add a action to the message to disable eslint for that folder. So the message will never reappear (see https://github.com/Microsoft/vscode-eslint/issues/122)

Any objection to close this issue?

**Comment by cheapsteak** [comment]
Is it possible to set the location of the eslint config?

An app ejected out of create-react-app has the configs in `/config/eslint.js`

A workaround is to either create a `.eslintrc.js` in the project root that only contains  

```js
module.exports = require('./config/eslint.js');
```

Or move the config back out to the root

Neither is ideal (bending the project to satisfy the editor). Would hope to be able to tell the plugin where to look for a config via a workspace setting

**Comment by dbaeumer** [comment]
You can configure this using the following VS Code setting: `eslint.options.configFile`
