### ISSUE TITLE
Codespace: Only provided options to reset?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-eslint#1089]
Clicking the crossed out icon at bottom in the status bar I expected to have the option to allow eslint in this workspace but instead I'm only given options to reset?

![image](https://user-images.githubusercontent.com/8586769/95801331-dc9c3680-0cae-11eb-8e31-eb7182949d1b.png)

**Comment by dbaeumer** [comment]
The problem is that I can't relate the `GitLens` welcome editor to any meaningful setup. Do you see the same when pressing the button on the `README.md`

**Comment by JacksonKearl** [comment]
Could it maybe not show up then? I have another codespace (JacksonKearl/CAHours), which does not use ESLint at all, but when the GitLens editor is open the entry appears in the status bar. If I open any other editor it goes away (replaced by prettier).

**Comment by dbaeumer** [comment]
For the status item we decided that if there was a request to load ESLint and it has not been approved yet we show this in the status bar with the item even if the current editor is not validated using ESLint. The reason is that ESLint is actually in an blocked / unconfirmed state.

I am pretty sure that the fact that you opened the `Readme.md` triggered this and not the welcome editor.

**Comment by JacksonKearl** [comment]
I don't think so.. the repo has no eslint bits at all, and when I first start it I get only the gitlens editor appearing, but there's still a status bar entry for eslint.

**Comment by dbaeumer** [comment]
That sounds wired. Let me check this.

**Comment by dbaeumer** [comment]
I tested with a workspace without ESLint installed and I even don't see the status bar item for JS files. Are you sure you don't have ESLint installed globally?

**Comment by JacksonKearl** [comment]
Can I have it installed globally in a fresh codespace? I don't have any dotfiles.

**Comment by dbaeumer** [comment]
OK. I tested it with `JacksonKearl/CAHours`  and there I get a status with a check-mark when opening a TS file which is actually correct since ESLint server runs but no file can be validated since no `eslintrc.json` file exists. However what I should do when clicking on the status icon is to simply bring the ESLint output to front.
