### ISSUE TITLE
Using ${workspaceRoot} in "configFile" field not working

### ISSUE THREAD

**Issue by agelter** [microsoft/vscode-eslint#1099]
I expected to be able to do something like:

`"eslint.options": {
        "configFile": "${workspaceRoot}/.eslintrc",
        "useEslintrc": false
    },`

However, this doesn't appear to be working.  For example, if `${workspaceRoot}` were to point to `/my/workspace/root/`, the parser is instead returning:

`/my/workspace/root/${workspaceRoot}/.eslintrc`

Specifically, it is doing the lookup correctly and is pasting it in, but isn't removing the `${workspaceRoot}` text.

**Comment by dbaeumer** [comment]
The reason for this is that VS Code itself has no support for this. See https://github.com/microsoft/vscode/issues/2809

I will close this as upstream since there is nothing I can do without proper API (I don't want to be in the business of reinterpreting this on my end).

One tip: you can use relative paths. The ESLint extension will run ESLint relative to the workspace folder or relative to the working directories setting.
