### ISSUE TITLE
Linters fail to work after the version update

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#110]
_From @Stephn-R on August 6, 2016 6:29_

- VSCode Version: 1.4.0
- OS Version: Mac (El Capitan) 10.11.16

Steps to Reproduce:

1. Download ESLint from the marketplace
2. Enable it by reloading Visual Studio Code
3. Attempt to generate an eslint error (i.e. Write an incomplete function declaration)
4. No errors show when an error should be detected

_Copied from original issue: Microsoft/vscode#10229_

**Comment by waderyan** [comment]
I cannot repo this. I have the same version and the same OS but ES Lint is working. 

![image](https://cloud.githubusercontent.com/assets/2449568/17599847/decb4f4a-5fb5-11e6-90cb-13a9858813f6.png)

**Comment by dbaeumer** [comment]
@Stephn-R any additional steps to reproduce this ?

**Comment by Stephn-R** [comment]
No need to reproduce or continue. I have not been able to replicate the
issue since the latest versions of vscode.

-- 
Stephen Rodriguez

On September 14, 2016 at 3:51:27 PM, Dirk Bäumer (notifications@github.com)
wrote:

@Stephn-R <https://github.com/Stephn-R> any additional steps to reproduce
this ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode-eslint/issues/110#issuecomment-247132832>,
or mute the thread

**Comment by dbaeumer** [comment]
Thanks. Closing then.
