### ISSUE TITLE
2.1.10 version of vsix is missing

### ISSUE THREAD

**Issue by rimasirich** [microsoft/vscode-eslint#1169]
Hi,
Is it possible to upload the latest 2.1.10 version of vsix to the GitHub release?
Thanks,
Rima

**Comment by dbaeumer** [comment]
The releases are uploaded to the VS Code marketplace. I only upload releases to the GitHub page if they are experimental or pre-releases. You can also get old releases from the marketplace.

And the latest release is 2.1.14.

Closing. Please ping if you still need support with this.

**Comment by rimasirich** [comment]
Hi @dbaeumer ,

Thank you for your response. We are downloading .vsix during the docker build so it is very convenient for us to download it from the releases ;) If you don't mind to upload it to the releases, we would very appreciate it :)

Thank you in advance,
Rima

**Comment by dbaeumer** [comment]
@rimasirich actually I have to say no on this since I don't have any plans to maintain two places where I publish releases. 

Are you using VS Code remote for docker? If so the `devcontainer.json` can contain extensions to install from the marketplace which will do all the magic for you. You can also have an `.vscode/extensions.json` in the workspace folder which list the extensions to install.
