### ISSUE TITLE
ESLint No config file found should offer to disable ESLint for that workspace or to run eslint --init.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#122]

**Comment by Elarcis** [comment]
I think it could be interesting to see what the TSLint extension does in this regard, to provide some kind of consistency, since TSLint and ESLint are somewhat very similar.

imho, I prefer having no ESLint warning at all if it doesn't find an .eslintrc, but being able to create one if I search for the related command.

**Comment by dbaeumer** [comment]
With the latest update you get a status bar item now which informs you about problems. I also talked to the tslint dev and they will adopt this approach.

![capture](https://cloud.githubusercontent.com/assets/1931590/18513851/66fe167e-7a8f-11e6-82ed-db74cd9f04a1.png)

I still want to disable the eslint on the workspace as soon as we have extension API to write settings.

**Comment by dbaeumer** [comment]
I added two commands to enable and disable ESLint. These will only be available if a workspace folder is open since changing a global setting can be very confusing.
