### ISSUE TITLE
Add blurb for approval flow to beginning of documentation

### ISSUE THREAD

**Issue by karlrwjohnson** [microsoft/vscode-eslint#1255]
This is a user onboarding issue that can be quickly solved with a bit of documentation:

Immediately after installing this extension, it seems like it doesn't scan _any_ files until you click the ESLint status bar item and click "Allow" on the modal.

![screenshot of the modal in question](https://raw.githubusercontent.com/microsoft/vscode-eslint/main/images/2_1_10/eslint-dialog.png)

The only documentation for this step appears to be in the [changelog for Version 2.1.10](https://github.com/microsoft/vscode-eslint#version-2110).

My impression is that this extension is basically useless without performing a manual post-installation step, but the documentation for that step is buried in a changelog where no one's going to see it.

Can the first paragraph include a blurb saying to "Click X and then Y"?

---

To be clear: I'm _not_ a regular user of VSCode (I use a different editor), but I work with people who choose to use it. When I tell someone they need to use ESLint for a project, they find this plugin, install it, and become confused why it doesn't do anything. They check in unlinted code, and there's pain all around. (I know CI/CD should be able to enforce this, but I don't have control over that right now.)

**Comment by dbaeumer** [comment]
@karlrwjohnson the is more general work for this underway in VS Code itself. See all the work around trusted workspaces. The result of that work will be that this dialog will go away and a more user friendly guide dance will happen in VS Code itself. See https://github.com/microsoft/vscode/issues/106488

I will close this issue since I am in the process to convert to that new concept. (see branch https://github.com/microsoft/vscode-eslint/tree/dbaeumer/workspaceTrust)
