### ISSUE TITLE
Enabling shareable config option in vscode-eslint extension

### ISSUE THREAD

**Issue by Hitesh235** [microsoft/vscode-eslint#1381]
Can we have an **option to enable a shareable config from the vscode-eslint extension** itself so that the config can we shared across the entire vscode irrespective of the .eslintrc.json configuration which will be available in a given JS/TS project ?

Can we have something similar like this ? or is it available ? extending the shareable config via .**eslintrc.json** through 
{

  "extends" : "myshareable-config"

}

assuming that **myshareable-config** is listed as the dependency in the project's package.json.

**Comment by dbaeumer** [comment]
@Hitesh235 I think that this should be possible. Best to do is to make it work when running ESLint in a terminal. Then it should work in the extension as well.

I will close the issue as a questions since there is nothing I can do about it in the extension since the extension solely relies ESLint concepts to resolve configuration files.

**Comment by Hitesh235** [comment]
Thank you @dbaeumer  That answered my question and I was able to configure the shareable config at User level so that the eslint extension will have the same.
