### ISSUE TITLE
Can't get rid of "Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser."

### ISSUE THREAD

**Issue by jakubmazanec** [microsoft/vscode-eslint#1458]
`vscode-eslint` can't handle switching between packages in a TypeScript monorepo and linting correctly. When I work on two packages in the same repo, it seems that wrong `tsconfig.json` is loaded when linting the files from the second package, resulting in error `Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser. The file does not match your project config: src\index.ts. The file must be included in at least one of the projects provided.`.

Steps to reproduce:
1) Clone [vscode-eslint-monorepo-bug](https://github.com/jakubmazanec/vscode-eslint-monorepo-bug)
2) Run `npm install`
3) Open VS Code
4) Open file `packages\app1\src\index.ts`
5) Two ESLint errors should appear on line 1, complaining about usage of `var` and unused variable.
6) Open file `packages\app2\src\index.ts`
7) Same two errors as in step 5 should appear, but instead above mentioned parsing error appears.

Previsously I had `eslint.workingDirectories` in `.vscode\settings.json` set to `[{"mode": "auto"}]`, but with the same result.

When running `npm run lint` from the root of the repo, ESLint works fine.

Maybe there's another setting I'm missing? Thanks for help.

**Comment by ChrisDryden** [comment]
I just came across the same issue in my monorepo with a very similar setup, my understanding is that the eslint.workingDirectories should be able to specify when you need to reload the .eslintrc, but when adding statements into the .eslintrc I see that it is only read once and not loaded for the second time when the new file is loaded. This is why it's not being registered as part of the tsconfig file since its basing that file structure on the other workingDirectory.

**Comment by jakubmazanec** [comment]
Also I remembered that I had `eslint.workingDirectories` set to `[{"mode": "auto"}]` and it used to work; it broke sometime last year.

**Comment by dbaeumer** [comment]
The underlying problem is how typescript works. A file needs to go into a project. Since you don't let TS ESLint know about this assignment TS tries to do its best but fails for the second project. 

The recommendation is to have a `eslintrc` file in each app1 and app2 and point to the corresponding tsconfig.json file. You can take this https://github.com/microsoft/vscode-eslint/blob/79d1e0dae146bb6cc9c7ffbeb02414b7e0c0f4c0/client/.eslintrc.json#L5 as an example on how to do this.

Let me know if this works for you.

**Comment by dbaeumer** [comment]
Just to note. It works in the terminal since a new process is launch on each validation.

**Comment by ChrisDryden** [comment]
https://github.com/microsoft/vscode-eslint/issues/1296 I might be coming across this issue instead it describes a similar scenario

**Comment by dbaeumer** [comment]
@jakubmazanec Sorry, didn't see that.

Actually I think it does makes sense that this config file is only loaded once since the server only loads the library once (otherwise validating on type had very bad performance implication). Referring to global state (`process.cwd()`) in that model can caused problems.

Any objection to close the issue since there is little I can do to fix this.

**Comment by jakubmazanec** [comment]
@dbaeumer Yes, that makes sense. Thanks again for the help.

**Comment by giorgiogross** [comment]
Ran into similar issues when vscode would set the `cwd` to the first sub-directory with an open file in the editor, which then would cause issues when using `process.cwd()` in the base eslint config file every time I was opening a file in a separate project in that monorepo. I have different `tsconfig.eslint.json` and `eslint.config.js` files in each project, inheriting from a base config provided in `packages/linter-configs`.

Using each eslint config's file location to resolve the right tsconfig.eslint.json worked (I use flat configs):
```
// In each package using the base config:

import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

import { makeBaseTseslint } from '@my-repo/lint-config/eslint-base';
import tseslint from 'typescript-eslint';

export default tseslint.config(...makeBaseTseslint(__dirname), {});
```
