### ISSUE TITLE
eslint.rules.customizations should override rule set to off

### ISSUE THREAD

**Issue by tylerprice1** [microsoft/vscode-eslint#1529]
I'm not sure if this is a Bug or Feature Request.

My repository's `.eslintrc` has `"react-hooks/exhaustive-deps": "off"`. I want to change this to `"warn"` locally, but setting it in `eslint.rules.customizations` does not seem to work. If it is set to `"warn"` in `.eslintrc`, I can change the severity of the warning (to `"error"`, for example), and that works correctly, but I can't change the rule from `"off"` to another severity. My team doesn't want to change it in `.eslintrc`.

How `.eslintrc` is configured:
```json
{
  "rules": {
    "react-hooks/exhaustive-deps": "off"
  },
  "plugins": ["react-hooks"]
}
```

How `settings.json` is configured:
```json
{
  "eslint.rules.customizations": [
    { "rule": "react-hooks/exhaustive-deps", "severity": "warn" }
  ]
}
```

**Comment by dbaeumer** [comment]
I am not sure if this will be possible since this feature depends on the ESLint `overrideConfig` feature. If you provide me with a GitHub repository that demos this that I can clone I will have a look and see if there is something I can do.

**Comment by MariaSolOs** [comment]
So I haven't debugged this carefully but just from reading [this code](https://github.com/microsoft/vscode-eslint/blob/4b92c12af15d41f76417bde9571cb56f08ec3d0f/server/src/eslint.ts#L1025-L1053) I think that the problem is that ESLint will lint according to the `.eslintrc` file it finds, and if a certain rule is off then no error messages will be generated for it and so the overrides won't do anything.

*Maybe* if you use [overrideConfigFile](https://eslint.org/docs/developer-guide/nodejs-api#eslint-class) inside [eslint.options setting](https://github.com/microsoft/vscode-eslint/blob/4b92c12af15d41f76417bde9571cb56f08ec3d0f/package.json#L92-L96) it will work, because then that configuration will be used to create the respective linter object.

**Comment by dbaeumer** [comment]
@MariaSolOs is actually correct. Only `eslint.codeActionsOnSave.rules` uses override config. The reason why `eslint.rules.customizations` is only hiding the problem is that otherwise auto fixing these errors on save wouldn't work. So this is actually by design.

**Comment by tylerprice1** [comment]
@MariaSolOs @dbaeumer, Thank you both! I'll close this

**Comment by DerZyklop** [comment]
@MariaSolOs’s solution works great.

I had a `.eslintrc.json` in my project.
I added a `.eslint-experimental.json` beside it, with rules that not all devs should get in their editors. 
Everyone who wants to additionally see our experimental rules needs to add this in the personal VSCode User Settings: 
```
"eslint.options": {
  "overrideConfig": {
    "extends": ["./.eslint-experimental.json"]
  },
},
```
