### ISSUE TITLE
I keep getting this error, please any help :)

### ISSUE THREAD

**Issue by mouadhx04** [microsoft/vscode-eslint#1530]
Oops! Something went wrong! :(

ESLint: 8.24.0

ESLint couldn't find the config "airbnb-base" to extend from. Please check that the name of the config is correct.

The config "airbnb-base" was referenced from the config file in "/root/mouadh/.eslintrc.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

**Comment by MariaSolOs** [comment]
@mouadhx04 Did you install `eslint-config-airbnb-base` inside your project? According to [these docs](https://www.npmjs.com/package/eslint-config-airbnb-base) it also seems like you need `eslint-plugin-import`.

Also the error message that you're getting seems to be referencing a personal configuration file (since it lives at the root of your user folder). Those are [deprecated](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#personal-configuration-files-deprecated) and result in problems like this, so you might want to move your `.eslintrc` configuration to the specific workspace that you want to lint and install all the necessary dependencies locally.

**Comment by mouadhx04** [comment]
thanks for feedback, this my package.json and .eslintrc but stil the same error message

![1](https://user-images.githubusercontent.com/85496711/193420655-13d6934e-00b3-437a-80c5-bf0265b12902.PNG)


![2](https://user-images.githubusercontent.com/85496711/193420660-1752d1c9-912f-48d3-b640-02f5890525be.PNG)

**Comment by MariaSolOs** [comment]
@mouadhx04 what's the path of that `package.json` file? Did you read these 2 notes carefully?
![image](https://user-images.githubusercontent.com/62502207/193421192-30b0e6a6-f95c-406f-8a80-fafd7fceaa4a.png)

**Comment by mouadhx04** [comment]
this is my project directory

![3](https://user-images.githubusercontent.com/85496711/193421524-20b79a59-d8da-4f50-90f6-bc52648f3b68.PNG)

**Comment by MariaSolOs** [comment]
Can you lint from the terminal using the CLI?

**Comment by mouadhx04** [comment]
when i lint i get this this

![4](https://user-images.githubusercontent.com/85496711/193426624-51a1b5ed-0f3c-430d-9c16-5f06289627dd.PNG)

**Comment by MariaSolOs** [comment]
Try adding `root: true` to your `.eslintrc` file.

**Comment by mouadhx04** [comment]
still the same error

![5](https://user-images.githubusercontent.com/85496711/193429343-aecd035a-57df-4736-b225-c500c14c373a.PNG)

**Comment by MariaSolOs** [comment]
Delete that other config file in your user folder or remove the extends setting from it.

**Comment by mouadhx04** [comment]
i tried for both but nothing change, it's the same error msg

**Comment by MariaSolOs** [comment]
Well if you're getting errors from a file that you removed, then something beyond linting is wrong with your setup.

At this point I would suggest restarting VS Code, cleaning up your `node_modules` folder and re-installing everything.

**Comment by mouadhx04** [comment]
i delete the directory and re-installing everything with different ways, then i type "npx eslint filename.js, i get the same error every time. yes probably i have problem in the setup ...

**Comment by dbaeumer** [comment]
@MariaSolOs thanks for all your help here.

@mouadhx04 the VS Code ESLint extension is based on the ESLint npm module. It basically makes it work nice in the editor. This means that if validation fails with ESLint in the terminal it will fail in the extension as well. 

If it fails in the terminal (as it does for you) then the recommendation is to first to to get it working in the terminal and to seek help from the ESLint community (for example here: https://stackoverflow.com/questions/tagged/eslint)

If you have a running setup in the terminal and see problem with the VS Code integration please open an issue in this repository and we are happy to assist.

I will close the issue for now since there is not much we can do from a VS Code extension perspective. Please ping if you think there is something we can help with.
