### ISSUE TITLE
how to specify custom formatter for error messages

### ISSUE THREAD

**Issue by mvayngrib** [microsoft/vscode-eslint#1532]
i'd like the UI to show me the error message as formatted by a [custom formatter](https://eslint.org/docs/latest/developer-guide/working-with-custom-formatters) that i can usually specify with the `eslint -f ./path/to/custom-formatter.js`. Currently it always uses the default formatter. Is this possible? Alternatively, how would i pass the `-f` CLI option through to eslint

thank you!

**Comment by dbaeumer** [comment]
I think that is currently not possible. May be by using `eslint.options` but I never tried it.

**Comment by mvayngrib** [comment]
i tried eslint.options before opening this issue but couldn't wrangle it. If you have any dirty workarounds u can think of in the meantime, please lmk!

**Comment by mvayngrib** [comment]
@dbaeumer alternatively, if u know how this should be implemented, i can try to find someone to work on it

**Comment by MariaSolOs** [comment]
@mvayngrib I can try looking into it.
To ease my investigation, do you have a project where you're trying to attempt this so that I can play around with it?

**Comment by MariaSolOs** [comment]
@mvayngrib Okay yeah I'm actually quite sure of what's missing but having your specific use case to verify my hypothesis would be great ;)

**Comment by mvayngrib** [comment]
hi @MariaSolOs , thanks in advance! Here's a demo repo illustrating the issue https://github.com/mvayngrib/eslint-formatter-example

i do see one potential issue and that's that the formatter returns string output rather than a list of strings per message, so idk how the plugin could pick that up 🤔. It'd be cool to be able to provide a per-item formatter to the plugin though, then that code could be reused for the CLI output and the plugin

**Comment by MariaSolOs** [comment]
@mvayngrib Hmmm you're right, this is actually a bit more complicated than I initially thought.

So basically we don't need to format the entire linting result objects (things like the squiggle location must remain unchanged for the error list to display the right things), just the message strings. That is, if I understand correctly, your request is to customize the `message` property of [this type](https://eslint.org/docs/latest/developer-guide/nodejs-api#-lintmessage-type). Because ESLint doesn't offer such an API, we would need to expose one from this extension, something like a setting that indicated the path to a `messageFormatter` that takes the output messages and then you apply your desired customizations. I'm not against that, but it also feels very specific to your need.

Alternatively, and yes this is a terrible hacky idea, you could modify the ESLint code itself inside `node_modules`. This extension invokes [`lintText`](https://eslint.org/docs/latest/developer-guide/nodejs-api#-eslintlinttextcode-options), so you can modify those output results as you like.

**Comment by mvayngrib** [comment]
closing this for now. Thanks for brainstorming this with me!
