### ISSUE TITLE
Where is the vscode-eslint cache stored?

### ISSUE THREAD

**Issue by distante** [microsoft/vscode-eslint#1544]
Hi I want to access the eslint cache so I can also use it on a commit hook (with `--cache-location`) , but I can not find any info about where the vscode-eslint cache is stored.

Can anyone point me in the right direction?

Thanks!

**Comment by dbaeumer** [comment]
It uses the location configured for ESLint. If you want to specify a location you can use the setting `eslint.options` with values listed here: https://eslint.org/docs/latest/developer-guide/nodejs-api#-new-eslintoptions

**Comment by distante** [comment]
Thank you!

**Comment by distante** [comment]
> It uses the location configured for ESLint. If you want to specify a location you can use the setting `eslint.options` with values listed here: https://eslint.org/docs/latest/developer-guide/nodejs-api#-new-eslintoptions

eslint does not have a cache configuration outside of the eslint cli. So maybe this needs to be an option of the plugin?

**Comment by ghaschel** [comment]
I believe so. But as ESLint itself doesn't support cache when using lintText, what if there was an option in the plugin to use lintFiles instead of lintText for the onSave validation?

This would be very beneficial since ESLint can easily get out of hand with its performance, even if it is in a very specific scenario
