### ISSUE TITLE
CodeHelper cpu 100%

### ISSUE THREAD

**Issue by JustDenP** [microsoft/vscode-eslint#1546]
Darwin 21.6.0 arm64. vscode 1.73.0
Immediately after opening a small typescript project, my MacBook temperature instantly rises to 80 degrees.

There are 2 code helper processes in monitorcontrol, one of which takes 100% of the cpu even after exiting vscode completely.

The problem is solved after disabling the eslint plugin, but it is impossible to work without it

**Comment by dbaeumer** [comment]
This is very likely caused by one of the plug-ins used in ESLint itself. 

What happens if you validate the same file in the terminal. Will it produce high CPU load? If so please try to make sure it doesn't happen in the terminal.

If it doesn't happen in the terminal, could you set `"eslint.debug":true` and look into the ESLint output channel if you see some wired activity in the log.

If this doesn't help, can you then provide me with a GitHub repository I can clone that demos what you are seeing.

**Comment by dbaeumer** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!
