### ISSUE TITLE
Add support to disable linting for unsaved files.

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-eslint#1562]
![image](https://user-images.githubusercontent.com/41773861/204216909-f977fe7a-c840-4897-bc45-4893d375f88e.png)

This file is created by https://github.com/tjx666/vscode-adobe-extension-devtools/blob/master/src/photoshop/descriptorInfoEditor.ts#L15

I find eslint lint this file but doesn't use the eslint config in my project root

**Comment by MariaSolOs** [comment]
That's really weird, the file type is `jsonc` which ESLint shouldn't even be trying to lint at all...

Could you please share the contents of your `.eslintrc` file?

**Comment by MariaSolOs** [comment]
However from the included picture it does make sense that the `.eslintrc` file with the arrow isn't being used for that JSON file, since that JSON file isn't a child in the folder structure. Try running `npx eslint --print-config filename`, where `filename` is the path to that JSON file.

**Comment by tjx666** [comment]
> Try running npx eslint --print-config filename, where filename is the path to that JSON file.

That file doesn't exists on desk, it is a untittle file but renamed.

check here: https://github.com/tjx666/vscode-adobe-extension-devtools/blob/master/src/photoshop/descriptorInfoEditor.ts#L15

**Comment by strindhaug** [comment]
> Actually, you currently can't disable eslint validation for an untitled file if the file type is configurated to be validated. If an untitled file is validated, it is validated in the context of the workspace folder. 

Why on earth isn't this an option from the beginning?!

Are we supposed to use a different editor to store our copy-pasted snippets? Or is there some other feature I don't know about to store random copy pasted crap into that is _not_ autolinted without any option to turn linting off?

It would not be as annoying if only it waited until we saved or if the auto-guessing of file-type didn't so aggressively guess filetype despite what I'm pasted only vaguely looking like valid js.. (I've even gotten eslint errors on css snippets and paragraphs of texts pasted into a new empty file just because of one random camelCase word made it stupidly assume it was Javascript somehow...)
