### ISSUE TITLE
Add back the ESLint status bar indicator

### ISSUE THREAD

**Issue by yellowjacketcoder** [microsoft/vscode-eslint#1601]
Type: **Feature Request/Removed feature reversal(?)**

# Summary
v2.4.0 removed status bar indicator in favour of Language Status, this hides the easiest access to eslint output logs alongiwth increasing the required clicks to 2, there was also no indication that the status indicator is moved to language status

# Solution
Add an **option** / add back the configuration setting "eslint.alwaysShowStatus" to still show status bar indicator like it did before v2.4.0 for those who prefer it over the language status

**Comment by dbaeumer** [comment]
I did the change to conform with thwe UI guidelines of VS Code to use a Language Status indicator instead of my own status bar item. You can pin the item using the pin in the language status. You can then click that pinned status item and it will open the ESlint output channel. 

Doesn't that work for you?

**Comment by yellowjacketcoder** [comment]
You are absolutely right and I am an idiot. I am very sorry and am closing this issue
