### ISSUE TITLE
can't install in remote containers anymore: RequiredArgumentMissing / no support for targetPlatform linux-arm64

### ISSUE THREAD

**Issue by sickssickssicks** [microsoft/vscode-eslint#1606]
As title says. Just recently it stopped being supported on all my docker containers.

Vscode throws error when installing: RequiredArgumentMissing

It's fetching extension from here: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dbaeumer/vsextensions/vscode-eslint/2.4.0/vspackage?targetPlatform=linux-arm64

Which errors out:

`
{
  "$id": "1",
  "innerException": null,
  "message": "Version 2.4.0 for extension dbaeumer.vscode-eslint has no support for targetPlatform linux-arm64",
  "typeName": "Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionVersionHasNoSupportForRequestedTargetPlatformsException, Microsoft.VisualStudio.Services.Gallery.WebApi",
  "typeKey": "ExtensionVersionHasNoSupportForRequestedTargetPlatformsException",
  "errorCode": 0,
  "eventId": 3000
}
`

**Comment by dbaeumer** [comment]
@sickssickssicks how did you trigger the install. This is very likely a dup of https://github.com/microsoft/vscode/issues/173215. Can you please add your findings there.

@sandy081 fyi

**Comment by daniel-pledge-io** [comment]
Commenting here since the above ticket is closed.

I still cannot install extensions that are already installed on my Remote Extension Host into my vs code dev containers.

However, installing extensions which are not already installed on the host _fails_, but I am presented the option to download manually and I can install directly into the container from VSIX without issue.

Take ESLint (dbaeumer.vscode-eslint) as an example. I have it installed on my host, vs code in my dev container tells me `This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'Container node:14 ([container name])' to enable.` as expected.

Clicking `install in container`, fails with a pop up `RequiredArgumentMissing` exception:
<img width="967" alt="Screenshot 2023-03-10 at 11 23 47" src="https://user-images.githubusercontent.com/125913742/224305610-1af92ca2-9f2b-4a5a-a346-6fe10455934f.png">

 The `Window` logs contain:
```
2023-03-10 11:27:16.165 [error] RequiredArgumentMissing: Signature: RequiredArgumentMissing
    at Pi.download (/root/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/server/node/server.main.js:150:468)
    at async ee.x (/root/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/server/node/server.main.js:150:20845)
    at async ee.h (/root/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/server/node/server.main.js:150:18978)
```

This log error is the exact same as the one that appears when I try and install an extension that is not on the host.

About VS Code output from the dev container:

```
Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z (1 day ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.3.0
Sandboxed: Yes
```

**Comment by sandy081** [comment]
@daniel-pledge-io Please file an issue in the vscode repository.

**Comment by dbaeumer** [comment]
Closing the ESLint issue then.
