### ISSUE TITLE
Using the VSCode ESLint extension with Bash on Windows

### ISSUE THREAD

**Issue by dgieselaar** [Microsoft/vscode-eslint#163]
Hi,

I just installed Visual Studio Code and the ESLint extension in a fresh Win10 install. I have NodeJS + ESLint installed in Bash on Windows. I can't figure out a way to make the ESLint configuration aware of the ESLint install in BoW. Is there any way I can make them work together, or alternatively, what work would have to be done in the extension to enable this option, or is this out of scope for this project?

**Comment by dbaeumer** [comment]
If you refer to Bash on Windows you mean Windows Subsystem for Linux. If so I think it should still work if everything is install locally in the workspace. However if ESLint is installed globally in Linux/Bash then I think there is little I can do since the global node_modules are not visible to the node running native in Windows.

**Comment by dgieselaar** [comment]
Yeah, I mean Windows Subsystem for Linux. I've decided to install the npm modules on the host, because even if this works a bunch of other stuff will not and it should probably be fixed (if possible) at a higher level. Thanks for the help!
