### ISSUE TITLE
pnpm and `Parsing error: Cannot find module`

### ISSUE THREAD

**Issue by CvX** [microsoft/vscode-eslint#1718]
After migrating from yarn to pnpm I'm getting `Parsing error: Cannot find module '@babel/plugin-proposal-decorators'` error, but only in vscode,
`pnpm eslint index.js` in the terminal (even a terminal inside vscode) works fine.

<img width="584" alt="image" src="https://github.com/microsoft/vscode-eslint/assets/66961/e9effee2-9f62-435d-88dd-5b17cf77aa18">

### Repro
see https://github.com/discourse/mass-merge – `main` branch for the working yarn setup and `pnpm` branch to get the error.

### The full error (w/ truncated paths)

```
Parsing error: Cannot find module '@babel/plugin-proposal-decorators'
Require stack:
- node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/config/files/plugins.js
- node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/config/files/index.js
- node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/index.js
- node_modules/.pnpm/@babel+eslint-parser@7.22.15_@babel+core@7.23.2_eslint@8.51.0/node_modules/@babel/eslint-parser/lib/worker/babel-core.cjs
- node_modules/.pnpm/@babel+eslint-parser@7.22.15_@babel+core@7.23.2_eslint@8.51.0/node_modules/@babel/eslint-parser/lib/worker/handle-message.cjs
- node_modules/.pnpm/@babel+eslint-parser@7.22.15_@babel+core@7.23.2_eslint@8.51.0/node_modules/@babel/eslint-parser/lib/client.cjs
- node_modules/.pnpm/@babel+eslint-parser@7.22.15_@babel+core@7.23.2_eslint@8.51.0/node_modules/@babel/eslint-parser/lib/index.cjs
- node_modules/.pnpm/@eslint+eslintrc@2.1.2/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.
```

---

I'm guessing that vscode-eslint (and/or eslint's API it uses) tries to resolve node_modules paths on its own, and those are different under pnpm? `@babel/plugin-proposal-decorators` in this particular case is a sub-dependency (i.e. not declared in the package.json of the project) so w/ pnpm it's not present directly in node_modules directory.

**Comment by dbaeumer** [comment]
I test it with npm as well and your setup works there as well. So this seems to be something special with `pnpm` which I first need to understand. All I can recommend for now is to add `@babel/plugin-proposal-decorators` to your dev dependencies which I tested and it works.

**Comment by dbaeumer** [comment]
The reason for this is that `pnpm` tweaks the eslint script that is put into the `./node_modules/.bin` folder and adds some NODEPATH settings to is. In your case mainly: 

`/workspaces/mass-merge/node_modules/.pnpm/eslint@8.51.0/node_modules/eslint/bin/node_modules:/workspaces/mass-merge/node_modules/.pnpm/eslint@8.51.0/node_modules/eslint/node_modules:/workspaces/mass-merge/node_modules/.pnpm/eslint@8.51.0/node_modules:/workspaces/mass-merge/node_modules/.pnpm/node_modules`

which actually hard codes paths

`yarn` does something similar but yarn provides a tools that lets VS Code know about this (e.g. `yarn dlx @yarnpkg/sdks vscode`) SInce I don't know what the purpose of that tweaking is all I can recommend is to open an issue against `pnpm` to ask them to provide a similar tools as yarn does
