### ISSUE TITLE
Questions on probe vs validate

### ISSUE THREAD

**Issue by MarvinXu** [microsoft/vscode-eslint#1736]
I'm learning eslint and settings in vscode. As I try to understand what files does vscode-eslint validate, I came across these two settings which made me confused.

> eslint.probe - an array for language identifiers for which the ESLint extension should be activated and should try to validate the file. If validation fails for probed languages the extension says silent. Defaults to ["javascript", "javascriptreact", "typescript", "typescriptreact", "html", "vue", "markdown"].

> eslint.validate - an array of language identifiers specifying the files for which validation is to be enforced. This is an old legacy setting and should in normal cases not be necessary anymore. Defaults to ["javascript", "javascriptreact"].

From what I understand,
- they both define what language should be validated
- `validate` is a legacy so we only need to set `probe` to enable a new language (in normal cases)

But as I try to setup validation for json, with the `eslint-plugin-jsonc`, adding `json` to `eslint.probe` simply doesn't work. I have to set in `eslint.validate` as the plugin doc [suggested](https://ota-meshi.github.io/eslint-plugin-jsonc/user-guide/#editor-integrations). So is this a **abnormal** case?

I don't know if I understand this correctly. Can someone shed some light on this?

**Comment by dbaeumer** [comment]
The difference is as follows:

- probe tries to find a plugin but if it fails it doesn't validate the file.
- validate forces the validation even if a corresponding plugin can't be detected.

Since we don't have autodetection / probing for `jsonc` yet, you need to use validate.

Hope that helps.

**Comment by MarvinXu** [comment]
@dbaeumer Thanks for your quick reply! So why should I use probe at all if validate can work regardless of probing support?

**Comment by JoernBerkefeld** [comment]
hi @dbaeumer sorry for going into this really old issue again but im facing a similar issue at the moment:

ive written a plugin that handles 2 proprietary languages (salesforce ampscript and salesforce ssjs).
when i run eslint on the test fixture folder everything works and it does give me the expected outcome but in vscode's problem tab nothing appeared.
i tried adding the langauge ids to probe but it didnt do anything. only after i added them to validate did results start to pop up. am i doing something wrong in how i tell eslint that my plugin supports those languages despite this working fine with vanilla eslint? what needs to be there so that your extension can handle it.

    "eslint.validate": [
        "ampscript",
        "ssjs",
        "sfmc"
    ]

i dont like using validate because it acts as a whitelist, excluding other types which means my users have to make sure they add all types that are relevant to them when they also want to use my plugin.

the project in question is: https://github.com/JoernBerkefeld/eslint-plugin-sfmc


all that said: im really glad you created this extension. saved me tons of time and pain <3 great job!
