### ISSUE TITLE
ESLint extension keeps linting the whole workspace

### ISSUE THREAD

**Issue by metinc** [microsoft/vscode-eslint#1740]
In the Readme I read:

> The extension is linting an individual file only on typing.

This tells me that only files opened in VS Code should be linted and only when I type. However in the Output of ESLint I see it is constantly crashing because it is running out of memory.

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

It is a big project and running `yarn eslint ./` does crash with the same error which is okay because I can fix this by using `NODE_OPTIONS="--max_old_space_size=4096"`.

But why does the extension crash? I did not set `eslint.lintTask.enable` so from my understanding it should not lint the whole workspace. But it is constantly restarting which means it is hogging my CPU and filling RAM.

ESLint v8.48.0
ESLint extension v2.4.2

**Comment by dbaeumer** [comment]
The eslint extension very likely crashes because you are linting TypeScript files using rules that require type information. This will force the ESLint TypeScript plugin to parse all files to get proper type information. This is how the TypeScript plugin works.

You can increase the heap size for the extension as well using the following two settings `eslint.runtime` to point to a custom NodeJS version which supports a heap size > 4 GB  (which the one that comes with VS Code doesn't) and 'eslint.execArgv`

**Comment by chrispaton** [comment]
For anyone else that comes across this issue first - this solution was the one that worked around it for me: https://github.com/typescript-eslint/typescript-eslint/issues/1192#issuecomment-2071711326
