### ISSUE TITLE
Is there a way to limit frequency?

### ISSUE THREAD

**Issue by taoliujun** [microsoft/vscode-eslint#1766]
When I type part of the letter "cons" in "console.log, eslint immediately shows a red wavy line, of course I know that "cons" is wrong, but I will then type the full "console.log".

I mean, is it possible to do an eslint check 1000 ms after the code changes, or after the code is saved?

I configured `"eslint.run": "onSave"`, but when I am typing, it still gives me a red wavy line  right away.

I've also tried to follow the other issues to set up the following configuration, but it still lints onType.

```shell
  "javascript.validate.enable": false,
  "typescript.validate.enable": false,`
```

**Comment by taoliujun** [comment]
My mistake, it works fine with `.js,.ts` files, but failed with `.tsx` files.

**Comment by dbaeumer** [comment]
I will close the issue then. Please ping if you think there is still something that needs to be done by the Extension.

And please assure that the errors you see come from ESLint since they could come from a different validator as well. ESLint errors do have the [eslint] suffix in the problems view.
