### ISSUE TITLE
Feature request: support eslint.probe json, json5, jsonc

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/vscode-eslint#1786]
Forking from #1736 -> https://github.com/microsoft/vscode-eslint/issues/1736#issuecomment-1818513623:

> Since we don't have autodetection / probing for `jsonc` yet, you need to use validate.

I'd very much like to add this in. Would vscode-eslint accept a PR? And do you have any advice?

**Comment by dbaeumer** [comment]
PR more than wlecome.

The code is here https://github.com/microsoft/vscode-eslint/blob/89d07f2eee7e363b90bc6b69ea41e5f8bdb55e2f/server/src/eslint.ts#L975. It basically works like this:

- check if we have a special parser for the language. The known parsers are listed here: https://github.com/microsoft/vscode-eslint/blob/89d07f2eee7e363b90bc6b69ea41e5f8bdb55e2f/server/src/eslint.ts#L731
- some parser (currently only vue) need special treatment since they can also parser other languages (e.g. typescript). This is handled here: https://github.com/microsoft/vscode-eslint/blob/89d07f2eee7e363b90bc6b69ea41e5f8bdb55e2f/server/src/eslint.ts#L745
- and then there are plugins into parser which are listed here: https://github.com/microsoft/vscode-eslint/blob/89d07f2eee7e363b90bc6b69ea41e5f8bdb55e2f/server/src/eslint.ts#L753

Quickly checking json things might be easy by simply adding the json plugin to the `languageId2PluginName` here https://github.com/microsoft/vscode-eslint/blob/89d07f2eee7e363b90bc6b69ea41e5f8bdb55e2f/server/src/eslint.ts#L753
