### ISSUE TITLE
Eslint randomly stops working in vscode insiders build

### ISSUE THREAD

**Issue by dlong500** [Microsoft/vscode-eslint#219]
Platform: Windows 7 x64
vscode version: latest insiders build (as of 3/17/2017 10:50am)
vscode-eslint version: 1.2.7

Not sure exactly where to start searching for answers, but I'm using the latest vscode insiders build (updated every time a new build is released) and as of the last week or so eslint will randomly stop working.  What I mean by that is it will "freeze" whatever suggestions/warnings it is showing and any code editing does not change the suggestions/warnings.

When this happens I always have to close vscode and kill several zombie "Code - Insiders.exe" processes.  At that point I can restart vscode and things work again for minutes or hours until the issue repeats itself.  I'm not sure if this is a vscode issue or a plugin issue (or both), but I don't know how to debug the issue.

I'm happy to produce logs/info if someone wants to tell me what to provide.

**Comment by dbaeumer** [comment]
@dlong500 with suggestions do you mean code complete / IntelliSense. This comes from VS Code itself and not from ESLint. Regarding the errors: do they start with [js] or [eslint]?

**Comment by dlong500** [comment]
I'm talking about the errors/warnings from eslint.  Yes they do start with `[eslint]`.

**Comment by dlong500** [comment]
Any updates on this?  I'm also noticing an issue that others have mentioned where eslint appears to be processing extremely slowly.  For example, I can type something, hover over what I've just typed and watch the error/warning get updated at about a one-character-per-second rate.  This is really hurting productivity.

**Comment by dbaeumer** [comment]
We know about problems with very large files and validating them in ESLint. We know how to improve it but I haven't found the time yet to work on it.

If your files aren't large then it would be cool if you can share a reproducible example since I have no explanation why VS Code and the ESLint extension would act like you describe.

**Comment by dlong500** [comment]
I'll have to try to put something together.  The project I'm working on now is private so I can't share that, but anecdotally it hasn't seemed to make much difference what the file size is.  Most of my files are going to be less than 1000 lines (probably 300-700 lines on average).

Does it make a difference how many files are open in vscode?

**Comment by dbaeumer** [comment]
@dlong500 no, the number of files shouldn't make a big difference since ESLint only validates single file (no inter file dependencies). However what does make a difference is the time it takes to check a single file which can increase through plugins which do extensive checking. So usually the time it takes is proportional to the size of the file but can increase by some plugins as well. If you run eslint outside on the files doesn't it take a long time to check the file?

**Comment by dlong500** [comment]
There is definitely something odd going on, because the lag seems to get worse over time and can be improved temporarily by restarting vscode.  So (at least for me) it doesn't appear to only be related to the size of a particular file.  I'm sure there could be other vscode core issues going on (or other plugins affecting things as well), so I understand it could be hard to pin down (especially with the insiders builds).

I do wonder if it would make sense to have some type of configurable parameter to allow users to specify an idle timeout for the `onType` validation.  So, for example, we could have it wait until X seconds have passed with no typing before the validation occurs.

**Comment by dbaeumer** [comment]
@dlong500 although the issues might come from different source I will mark this one as a dup of #215. I makes communication easier and helps me track down the issue.
