### ISSUE TITLE
Support source attibute on Diagnostic

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-eslint#22]

**Comment by egamma** [comment]
@dbaeumer I don't see this support in the latest vscode-eslint version, has this changed been published yet?

**Comment by dbaeumer** [comment]
@egamma no, I didn't because of the problems with VSCode not supporting different extension versions. I published a patched version that has that support now.

**Comment by egamma** [comment]
Thanks!

Am 29.02.2016 um 15:40 schrieb Dirk B?umer <notifications@github.com<mailto:notifications@github.com>>:


@egamma<https://github.com/egamma> no, I didn't because of the problems with VSCode not supporting different extension versions. I published a patched version that has that support now.

-
