### ISSUE TITLE
Debounce keypresses?

### ISSUE THREAD

**Issue by oullah** [Microsoft/vscode-eslint#222]
ESLint seems to run on every keypress, and my machine falls behind. I have to wait after typing some code to see if there are any final errors when I'm done. Is there some way around this? I would like it to wait until I haven't typed for a second or two before running eslint.

**Comment by dbaeumer** [comment]
The client de-bounces right now for 200ms but then forces the error detection to not fall behind to far. However we need to do better for large files here were error checking takes more than 200ms. This is on the plan for the future.

Marking as upstream and closing since this has to happen in the base library we use for linter (vscode-languageserver-node).

**Comment by oullah** [comment]
Cool, I just saw that I can run the linter on save so I'll just do that.
