### ISSUE TITLE
Add support for .eslintignore

### ISSUE THREAD

**Issue by theel0ja** [Microsoft/vscode-eslint#238]
![image](https://cloud.githubusercontent.com/assets/5832930/25870702/b9f5a372-350d-11e7-856b-7d3e7d8e3c8f.png)

That's while `eslint .` isn't saying anything of that because I'm using `.eslintignore`, so this haven't support for it.

**Comment by dbaeumer** [comment]
The ESLint extension does have support for .eslintignore since it calls into the eslint npm modules.

@theel0ja can you share a workspace showing the problematic behavior. I can not reproduce this locally in my setup. 

![cast](https://cloud.githubusercontent.com/assets/1931590/25943156/3fac8814-363f-11e7-9f66-d2da1a2bded8.gif)

**Comment by theel0ja** [comment]
I'm using this `.eslintignore` and it's in `web/.eslintignore`:
```
public_static/
public_www/
views/
```

The file that I was editing was in `web/public_static/js/wb404.js`.

**Comment by dbaeumer** [comment]
@theel0ja this behavior is inherited by eslint. eslint (the tool run in a terminal) only honors eslint ignore file from the current working directory upwards not from the file linted. Since VS Code is opened I guess on a parent folder of the web folder the .eslintignore file is not honored. 

The ESLint extension does offer a working directory configuration to support these cases (it is comparable to you in a terminal do a cd into web and run eslint there). See the `eslint.workingDirectories` here https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint for how to set this up
