### ISSUE TITLE
Error while loading rule 'comma-dangle': "listener" argument must be a function

### ISSUE THREAD

**Issue by yoojene** [Microsoft/vscode-eslint#242]
Upgraded to the latest version this morning and now every time I save or navigate to anything this message appears in the error bar. _Pretty_ sure this was also happening before 1.12.2 as well..

![image](https://cloud.githubusercontent.com/assets/14247260/26104098/3035f96c-3a34-11e7-9d0b-aa69bd986330.png)

- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open VSCode
2. Observe error message in header

**Comment by timfoley** [comment]
I got that error message today! Then I found the typo I made. I thought it was a bug until I copied and pasted example code from the [ESLint docs](http://eslint.org/docs/rules/comma-dangle). Your case might be a bug, but it's worth knowing that it's also the error message you might get from a typo in your rules. 

**With error**
```json
    "comma-dangle": [1, {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-mulitline",
      "functions": "never",
    }],
```

**No error**
```json
    "comma-dangle": [1, {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "never",
    }],
```
It's a tough typo to spot!

**Comment by dbaeumer** [comment]
The ESLint VS Code extension doesn't do any config parsing itself. I only relies on the eslint npm module to do so. In case the parsing fails the npm module throws an exception which I present in an error message. Usually these exceptions show up when running eslint from the terminal as well. And the ESLint output channel mostly contains more info.

There is not much I can do about this besides telling the user that something is wrong with the config file. I also alter the ESLint status bar icon in this case.

I anyone has a nice suggestion how to improve this further please let me know.

I will close the issue since I think the extension already prints enough information about what is going on.
