### ISSUE TITLE
Integrate eslint server with other client

### ISSUE THREAD

**Issue by i328638** [Microsoft/vscode-eslint#301]
According to the server it supports IPC connection. I changed the connection to use a stream insted.

I have replaced the code of 'create connection' in the server with this code:
let connection = createConnection()

but it failed at https://github.com/Microsoft/vscode-eslint/blob/master/server/src/server.ts#L303

resultPromise = connection.workspace.getConfiguration({ scopeUri: uri, section: '' }).then((settings: TextDocumentSettings) => {
because connection.workspace is null (it's not a standard LSP connection).

I overcame this problem by creating a settings file locally and using resolveSetting on this file. 
Is there any other solution for this problem? A possible solution which I could use your code with no need to change any lines?

**Comment by dbaeumer** [comment]
@i328638 

- regarding createConnection: You need to change this to `let connection = createConnection(ProposedFeatures.all);` This is some I can change in code since it is not necessary to pass in the IPC readers a writers. The are determined via --node-ipc command line argument anyways.
- the eslint extension 1.3.x has support for multiple root folders. Therefore it needs to get the settings scoped to a resource. To do so it uses the new proposed LSP protocol getConfiguration which you would have to implement on the client side. See the ESLint client code as an example. The returned settings are of structure `TextDocumentSettings`

**Comment by amiramw** [comment]
Is this proposal documented somewhere? I couldn't find it anywhere in the language server repository/issues.

**Comment by dbaeumer** [comment]
How to propose new protocol is documented here: https://github.com/Microsoft/language-server-protocol/blob/master/contributing.md

For the workspace folder the issue is: https://github.com/Microsoft/language-server-protocol/issues/298
