### ISSUE TITLE
onClose action sends notification with empty diagnostics

### ISSUE THREAD

**Issue by avizov** [Microsoft/vscode-eslint#306]
When I open a file it sends to me the diagnostics but when I close it all the diagnostics are vanish. It looks that "onClose" action, it sends notification with empty diagnostics.   
In general (for example in jdt server), I expect that when I close the file the diagnostics remain the same unless I fixed the issues. In addition, I expect that when I open a file I get diagnostics for all project and not only for the opened file.
Is it a bug?

**Comment by dbaeumer** [comment]
No, VS Code has the rule that if you do single file validation (as ESLint currently does) the errors are cleared on close. If there is a project knowledge (e.g. for C#, Java, ...) then the errors remains. The reason is that errors should be consistent. If you open a workspace all errors should reappear the same as when you last closed the workspace. This would not be the case if we wouldn't clear the errors on close.

**Comment by avizov** [comment]
If I understood you correct the vscode-eslint is currently on single file validation and not in project level validation like for example the jdt server is. If this is the case, do you plan the vscode-eslint to support also in project level validation?
