### ISSUE TITLE
.eslintignore is not working

### ISSUE THREAD

**Issue by thinklinux** [Microsoft/vscode-eslint#309]
Uploading a screenshot. Maybe I am doing something wrong but the __test__ folder is not ignored for some reason.

![screen shot 2017-10-05 at 12 10 22](https://user-images.githubusercontent.com/326949/31219893-5af36e7a-a9c7-11e7-8be8-aa2a28696fa0.png)

VSCode 1.16.1
ESlint plugin version 1.3.2

**Comment by dbaeumer** [comment]
The reason is that .eslintignore files are only resolve relative to the current working directory which in our cause the folder that contains the server folder. Hence the file is not read.

ESLint as support to specifying working directories for layouts like the one you use. Please see https://github.com/Microsoft/vscode-eslint#settings-options

Ping if this are still unclear.
