### ISSUE TITLE
Do not activate eslint server for projects without eslint config files.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode-eslint#322]

**Comment by dbaeumer** [comment]
This is a chicken egg problem. Since ESLint has so many ways to provide a config file it is hard to tell if a file has a valid .eslintrc configuration. It is simply not enough to look for a .eslintrc.json file in the root. In ESLint itself even the name of the config file can be custom. So the only way to find this out is to start the ESLint server.

I will close the issue. The way how we decided to do this is by only showing a message once per workspace that no eslint configuration can be found.

**Comment by ravshansbox** [comment]
At least it's possible to make it configurable with something like, `eslint.requireExplicitConfigFile: true`.

**Comment by dbaeumer** [comment]
I still think that will be a slippery slope since such a setting will be force to honor all eslint config locations as well over time.

I think we should better have a setting to not show the output panel in case no validation can happen. And the eslint extension should stop the server if no validation can happen.

**Comment by dbaeumer** [comment]
I am open for PRs to address this.
