### ISSUE TITLE
CPU to 100% with JSX

### ISSUE THREAD

**Issue by jmhmd** [Microsoft/vscode-eslint#336]
I've been having an issue for a while now where the extension host process pegs the CPU. It always occurs when working with JSX, and most frequently seems to happen specifically when writing an html tag, before typing the closing tag. The eslint extension locks up displaying the error
```
[eslint] Parsing error: Expected corresponding JSX closing tag for <i>
Loading...
```
and the CPU goes to 100%.

I narrowed it down to the eslint extension with `ps aux | grep [pid]`, which output:
```
18758 100.0  0.9  3325716 143980   ??  R     8:56PM   0:58.79 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost

18761   0.0  0.4  3205280  60704   ??  S     8:56PM   0:06.34 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/username/.vscode/extensions/dbaeumer.vscode-eslint-1.4.0/client/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/username/.vscode/extensions/dbaeumer.vscode-eslint-1.4.0/server/out/server.js --node-ipc --clientProcessId=18758
```

Any help would be greatly appreciated, this issue makes it very frustrating to use vscode with JSX.

**Comment by dbaeumer** [comment]
@jmhmd please file the issue against vscode itself since the eslint server doesn't have any CPU load. 

I am pretty sure that this is caused by another extension you have installed. Please try to run with `--disable-exensions` to see if it still reproduces.

And there is a performance side here with instructions on how you can help the VS Code team to track down issues in the extension host : https://github.com/Microsoft/vscode/wiki/Performance-Issues
