### ISSUE TITLE
Linting files outside of the npm package?

### ISSUE THREAD

**Issue by bary12** [Microsoft/vscode-eslint#363]
I have ESlint installed in an npm package, but the npm package is only in a small part of my project.

```
project/
├── lib/
|    ├── .eslintrc
|    └──  A lot of files that should be linted.
├── tests/
|    ├── package.json
|    └──  node_modules/
|        └── .bin/eslint/
```

Only the files in tests/ are being linted. I've tried changing the working directory, installing eslint globally, no luck.

**Comment by dbaeumer** [comment]
@bary12 installing eslint globally should work. When you open a file from the libs folder what is printed in the ESLint output channel.

You can also use the `eslint.nodePath` setting to control the install location of the eslint npm modules.

**Comment by bary12** [comment]
ESlint output channel:

```
(node:19348) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 90): TypeError: missingModuleReported.has is not a function
(node:19348) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 91): TypeError: missingModuleReported.has is not a function

```

I have tried `"eslint.nodePath": "C:/Users/Bary/AppData/Roaming/npm"`. This is where the eslint package is installed globally, but it still didn't work.

**Comment by dbaeumer** [comment]
This is strange. The ESLint extension has no `missingModuleReported` var or property. If you run ESLint in a terminal does it work or will it result in errors as well.

**Comment by dbaeumer** [comment]
Sorry, my fault. Search in the wrong repository :-)

**Comment by dbaeumer** [comment]
This is very wired. `missingModuleReported` is a HashMap created in main and it fails since it doesn't offer a 'has' function which all Maps have. Which version of VS Code and ESLint are you using.

The reason why this happens is that ESLint (the npm module) requires all plugins and the npm module itself to be either installed locally or globally. Since the files in the lib directory are validated using the global eslint you need to install all needed plugins globally as well.

**Comment by bary12** [comment]
Thank you, I did forget to install the plugin globally and now it works.
