### ISSUE TITLE
Underlining entire object on eslint error

### ISSUE THREAD

**Issue by nrgraham23** [microsoft/vscode-eslint#370]
Hello,

This is the same issue as #278 but that issue is closed and locked.

Is it possible to simply underline the line where the error occurs instead of everything from line to endLine?

I presume that is what is happening based on https://user-images.githubusercontent.com/1931590/31603922-fccf7174-b261-11e7-82fe-2cd1ad4e5b8c.png

The vim plugin I have seen some co-workers using simply puts an error on the line where the problem first occurs (the 'line' field in the linked screenshot).

As it is, I may need to simply uninstall this plugin because there are files I cannot change with errors that fill my editor with red lines.

**Comment by dbaeumer** [comment]
As I outlined in #278 the error ranges come from the ESLint npm module and I am relectant to start to change them. This will cause other issues where user will complain about not underlining enough. All I could think of is a setting that controls this that is off by default.

A pull request implementing this is welcome.

**Comment by nrgraham23** [comment]
I'll look into what would be involved with adding an option (default off) that would cause multi-line errors to only underline the first line.  It will probably be a few weeks before I am able to get to this though.

Thanks.

**Comment by dbaeumer** [comment]
That is OK.

**Comment by dbaeumer** [comment]
https://github.com/Microsoft/vscode-eslint/issues/607 is asking for only underlying the first token.

**Comment by DanielSWolf** [comment]
I'm often in the situation that ESLint reports an error for a high-level AST element. For instance, here's a screenshot of `eslint-plugin-jest` reporting an error on a Jest unit test.

Within each unit test, the actual `expect` statement usually follows some amount of setup. As long as I'm writing this setup code, the test (the `it` node) is technically invalid according to the `expect-expect` rule because it doesn't include any `expect` statements. However, this means that about 80% of the time I spend writing unit tests, the entire function I'm writing is disfigured with red squigglies:

![image](https://user-images.githubusercontent.com/5963162/75225896-b66f6800-57ab-11ea-80c1-f0cb4c0bdc3d.png)

This doesn't just look bad. It also hides any actual errors I may have made. Only when I type the first `expect` do I see whether there are any other problems with my code.

Initially, I thought that the problem was with `eslint-plugin-jest`, and I created [an issue](https://github.com/jest-community/eslint-plugin-jest/issues/539) there. However, they replied that other IDEs just highlight the code belonging to the affected AST element itself, *not* its child elements. This is a screenshot of the same situation in IntelliJ:

![image](https://user-images.githubusercontent.com/3151613/75231931-34b72300-581b-11ea-8582-fa1ee619538b.png)

This is so much better. It clearly shows that there is an error with the `it` node, but it doesn't hide any additional errors *within* that node.

Could you please add an option to highlight errors the way IntelliJ does?

**Comment by dbaeumer** [comment]
@DanielSWolf this is nothing I can do in the ESLint extension since I don't have the knowledge (No AST, no information about how this is actually rendered). If this should be a setting then it has to go into VS Code itself or the jest plugin. I am actually the opinion that this would best be added to the jest plugin as on options since they are the only one that have the AST in hand.
