### ISSUE TITLE
Disabling Rules with Inline Comments (eslint-disable) doesn't work

### ISSUE THREAD

**Issue by JakubRimal** [Microsoft/vscode-eslint#398]
As it is described at https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments it should be possible to disable ESLint by comments but it seems like vscode-eslint plugin ignores it.

**Comment by JakubRimal** [comment]
Ok, now I've realized that it should be **block** comment when you use `eslint-disable` which is in contrast with the usage of `eslint-disable-line` and `eslint-disable-next-line` where it is possible to use inline comment.
This is a bit confusing as the [eslint package](https://www.npmjs.com/package/eslint) works with both types of comments.

**Comment by dbaeumer** [comment]
Hmm, this is strange since the eslint extension uses the eslint npm module to do the work. Does this work if you lint the file in a terminal using the same eslint npm module?

**Comment by JakubRimal** [comment]
You are right, my fault, I was confused as I thought that with eslint package it works because the build didn't fail. But it was only warning so the build should not fail.
Now I've tried that VS Code ESLint extension has exactly the same behavior as eslint in terminal so it works correctly and I'm sorry about that I've created this issue.

**Comment by samtsai** [comment]
In my case running `eslint` from command line produces no errors/warnings but in the Vue template it does.  Code displays the error for the rule: `vue/require-v-for-key` which I disabled via comments:
`<!-- eslint-disable vue/require-v-for-key, max-len -->`

I've combed through `eslint-plugin-vue` issues but haven't found any yet, especially since, running `eslint` in command line works as expected.
