### ISSUE TITLE
Code Helper process uses 100% CPU

### ISSUE THREAD

**Issue by Manc** [Microsoft/vscode-eslint#427]
The problems only started within, last 1 or 2 weeks, not exactly sure. The fans of my iMac start blowing and Activity Monitor shows **Code Helper** being constantly at around 99.9 to 100.0%.

I took the process ID as shown in Activity Monitor (in my case 77422) and ran `ps aux | grep 77422` in the terminal, giving me:

`77422  95.2  0.4  5111808 142308   ??  R     4:29pm   2:01.30 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-1.4.7/client/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-1.4.7/server/out/eslintServer.js --node-ipc --clientProcessId=77369`

It won't stop until I kill the process. Is there anything I may have done wrong or can anybody help me fix this? I find this plugin really useful and it'd be a shame if I had to disable it. Thanks!

**Comment by dbaeumer** [comment]
@Manc do you have steps to reproduce this on the code you are currently working on. If so can you share that code so that I can investigate. Without steps it will be very hard to track down.

There is additional things you can do: when it happens can you run eslint from the command line on exactly the same workspace and see what happens. If this produces high CPU load as well it is very likely a bug in ESLint npm module.

In addition you can enable logging for the eslint server. To do so add a setting `	"eslint.trace.server": "messages"`. A trace output will appear in the ESLint output channel. Then we would get an idea where it gets stuck.

**Comment by Manc** [comment]
@dbaeumer Thank you very much for pointing me into a direction. Running ESLint manually (with option `--debug`) causes the CPU consumption of the process go up to 100% and it gets stuck on (at least) one of my JavaScript files. Unfortunately I haven't figured out why that is yet, but it looks like it the problem has indeed nothing to do with this plugin.

Thanks for your help and thanks for this plugin! 🥇
