### ISSUE TITLE
config file fallback

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Microsoft/vscode-eslint#482]
Is there an option to have a global config file, but if the project has an eslint config file, it overrides the global config?

If not, it would be an awesome feature for those who work on different projects.

**Comment by dbaeumer** [comment]
@AbdelrahmanHafez this is actually the standard behaviour of ESLint since it looks for config files up the parent directory chain and takes the first one it find. So you can simply have one in your home directory which is taken when the project has none.

I will close the issue. Please ping if this was not helpful.

**Comment by AbdelrahmanHafez** [comment]
@dbaeumer 
This only works when we have a linear directory chain, I was hoping for something that could be used in the VSCode settings as a fallback instead of looking for directories, in order to keep all my settings in one folder.

The setting below has this behavior:
Works in all JS files, regardless of the directory. If I work on another project that has its own config file, it still uses the one in the settings.

Desired behavior:
The configFile in the settings works only if there's no eslintrc file in the project root.

```
"eslint.options":{
        "configFile":"E:\\Info\\localhost\\Web Development\\NodeJS\\autotash\\.eslintrc"
    }
```

The reason I am looking for this is that I try writing some quick stuff on the desktop, or on different partitions on my disk, and I don't want to have config files in each partition, or on my desktop, yet I'd like to have a fallback config file that works only if the project doesn't have a config file.

**Comment by dbaeumer** [comment]
I see. But the ESLint extension fully relies on the features of the ESLint npm module here (see https://github.com/eslint/eslint). I don't have any specific lookup code and I am very reluctant to add some since it will make the behavior different from whether you run ESLint from the extension or from a terminal. If you think such a feature is necessary please try to get it into ESLint itself.
