### ISSUE TITLE
eslint.provideTask works incorrectly in handling environment's specific

### ISSUE THREAD

**Issue by bam** [Microsoft/vscode-eslint#484]
As I could notice yesterday, eslint's detected task should adapt to OS and tries to run appropriate command, particularly it uses "\" or "/" in path to eslint executable.
But there is a problem when OS is Windows but integrated terminal is *nix (e.g. Git bash).
So eslint's task tries to run windows command `node_modules\.bin\eslint.cmd` in bash terminal and gets error that there is no such command.
Seems task should be able detect not the OS but the current terminal environment of VS Code.

P.s. also it seems that after running eslint's task output is not parsed to show errors in the Propblems panel (but it must be confirmed – I have no access to my windows laptop now)

**Comment by dbaeumer** [comment]
Yes, this is a know issue and is something that needs to be fixed on the VS Code end (see all the issues tagged with WSL in the VS Code repository). ESLint doesn't have any knowledge right now that the used terminal will be WSL bash. 

I will close the issue since the right fix for this will come from VS Code.
