### ISSUE TITLE
warning icon is slightly different than built-in vs code warning incon

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-eslint#487]
looks like the eslint one has sharper corners and a bold `!`.  these should be the same.

![image](https://user-images.githubusercontent.com/1487073/41376976-8c0ede96-6f0f-11e8-8ce0-e47f71362283.png)

**Comment by dbaeumer** [comment]
Agree, but hard to achieve. The problem is that ESLint uses the warning icon from the Octicon font using $(alert) in a text and to my knowledge status bar items can not set icons directly. So the only way to make this the same is to use Octicon icons in the core as well. Do you think we should do this?
