### ISSUE TITLE
".eslintignore" Not Work When Path Includes Chinese Char

### ISSUE THREAD

**Issue by xlfsummer** [Microsoft/vscode-eslint#517]
my folder structure:
```
- code
  - dist
    - a.js
- 代码
  - dist
    - a.js
- .eslintignore
- .eslintrc.json
```

 .eslintignore :
```
dist
```

"a.js" in "code/dist" was  ignored
"a.js" in “代码/dist” was not ignored

![image](https://user-images.githubusercontent.com/20750969/44001236-eeddd272-9e60-11e8-8698-e983e781b255.png)
(same content in two a.js files)

**Comment by dbaeumer** [comment]
@xlfsummer does this work correctly when you execute ESLint from the terminal directly. If so can you provide me with a GitHub repository that I can clone that demos the problem.

**Comment by xlfsummer** [comment]
Not correctly either.

Here is the repo:
https://github.com/xlfsummer/eslint-demo.git

**Comment by dbaeumer** [comment]
@xlfsummer thanks for the demo. I wasn't clear in my last post. If this also happens in ESLint in the terminal, then this is not a issue with the extension but with ESLint itself and the issue has to be reported here: https://github.com/eslint/eslint

Can you please do so since I can reproduce this in the terminal. 

<img width="626" alt="capture" src="https://user-images.githubusercontent.com/1931590/44648289-e1270780-a9e0-11e8-9d3c-6578f12b93bf.png">

**Comment by xlfsummer** [comment]
okay, sorry for opening an issue in wrong place, thank you.
