### ISSUE TITLE
Override global eslintrc if one is found in current project

### ISSUE THREAD

**Issue by slaughtr** [Microsoft/vscode-eslint#527]
I am currently the "eslint guy" at work. I have a decently customized .eslintrc that I have crafted over some time. I put this in my home directory, and point at it via `"eslint.options"`

Now, I'm beginning work on a new project, and I've convinced my team that we should use eslint. As the guy yelling about it, I graciously took on the task of getting everything set up and sharing those steps with others. I have pared down my .eslintrc to remove some of the more personal options, and put it in the root of the project. The issue is, I can't seem to figure out how to get eslint/VS Code to utilize this config file when I'm in this project. Obviously, I have config to point at my global config, but I would like to be able to auto-switch based on project. This is a major point I've sold for eslint, saying "You won't have to follow these rules outside of this project"...but apparently I was wrong?

Is there a way - without manually changing my VS Code settings - to load the eslintrc from the project root? The only way this will work is if I can make eslint utilize the project level config if it exists (and not do anything if it doesn't). I've tried `"eslint.workingDirectories"` to no avail.

EDIT: Would adding my (global) .eslintrc to my NODE_PATH and configuring that with eslint work?

**Comment by dbaeumer** [comment]
@slaughtr pointing to it via the `eslint.options` setting is like passing it on the command line in a terminal using the `--config`. If you do this ESLint respects this and will not use the one in the project folder.

However, what eslint does is it looks up the folder parent chain for a `.eslintrc` file. So if you have the following setup

```
home
  .eslintrc
  projects
    projectOne
      .eslintrc
    projectTwo
```

and remove the VS Code setting the following will happen

- code in project one will be validated using the local .eslintrc file
- code in project two will be validated using the .eslintrc file in your home directory

I will close the issue since what you describe is standard ESLint behaviour which I will not temper with in the VS Code eslint extension.

**Comment by slaughtr** [comment]
Ahhhhh so I really just need to move my global config to my project directory root? Jeez, I would never have thought of that, nevermind how obvious it is.

I have tested this, it works. Thank you!
