### ISSUE TITLE
Lint changed lines only

### ISSUE THREAD

**Issue by sebastian-nowak** [microsoft/vscode-eslint#546]
Hello,

is there a way to configure this extension to complain only about the lines that were changed? So only those that are reported by `git diff`, `git diff --staged` or something similar.

It would be super useful for large projects, where new linter rules are introduced and enforced for new code only. Otherwise everything is displayed in red.

Thanks,
Sebastian

**Comment by dbaeumer** [comment]
This is currently not possible.

**Comment by lee-b** [comment]
+1

Note that this ticket is requesting compliance with best practice.  Commits (and arguably even branches) should not be changing code unrelated to the commit, and so lines that aren't being changed shouldn't be reported as something to be fixed, by default.  Mixing bugfixes, new features, and general code cleanups is a mistake, and VSCode should not encourage that by default.

A separate "code cleanup mode" should be supported, as the non-default, for when people want to do passes over old code and generally clean things up or improve coding standards.

Additionally: tickets should not be closed simply because there are a lot of tickets to manage.  Get a better management system, or switch to kanban, or ignore all but your current ticket with GTD, but don't throw out the tickets! ;)

**Comment by jaycetan** [comment]
+1

The code base I work in has multiple teams contributing. That being said, there is no existing style guide in place. When formatting a page, code that does not belong to my team is formatted as well. Commits become convoluted as many lines are change when I had only meant to update a few lines.
