### ISSUE TITLE
Don't use local eslint unless it's explicitly listed in package.json

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode-eslint#549]
If I leave `eslint.nodePath` set to `null` (the default), and I edit an NPM project that does not have `eslint` explicitly listed in its `package.json`, yet one of its deps includes `eslint`, then this VSC extension will still use the local eslint rather than the global one. This is not preferred, because then global plugins will not be loaded.

**Comment by dbaeumer** [comment]
As a work around you can set `eslint.nodePath` to your global install eslint.

**Comment by dbaeumer** [comment]
Almost. The code 10 lines above needs to be changed to handle the case that only modules from the nodePath should be considered. Basically this line https://github.com/Microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L414 needs to pass in a different directory in the case `eslint.nodePath` is set to `null` explicitly. My be we can pass the global install location as well.

**Comment by dbaeumer** [comment]
Thinking about this again I have the feeling that this needs a setting as well since implementing this is a semantic breakage. Something like 'eslint.requirePackageDependency`. The default would be `true` to keep the current semantic.

This can not only be derived from nodePath since the resolver also takes global installs into account.
