### ISSUE TITLE
fdescribe / fit shows redlines on the entire block

### ISSUE THREAD

**Issue by maoryosef2** [Microsoft/vscode-eslint#557]
when using focused tests, vscode will show redlines on the entire focused blocked, instead of just showing it on the `fdescribe` / `fit` line

it is forcing me to disable eslint while working on specific tests
see example:

![image](https://user-images.githubusercontent.com/22167090/46913384-96634e00-cf94-11e8-8231-04c0673eba59.png)

**Comment by dbaeumer** [comment]
The reason is that the error is reported that way from the ESLint npm module (https://github.com/eslint/eslint) and so far I was very reluctant tempering with any of the information. I see your problem but I have no knowledge about when it would be appropriate to shorten the error range and when not. 

Any objection to close this?
