### ISSUE TITLE
The plugin do not clear Task reported errors

### ISSUE THREAD

**Issue by daiheitan** [Microsoft/vscode-eslint#56]
Currently `vscode-eslint` do not run lint through project, only on current file.

But I would like to know a list of all my errors through the project. So I defined a task to run `eslint` through the project.

Now I open an error and fixes it, but the marker is not cleared. I think as I've opened the file and modified something, `vscode-eslint` should be triggered and do something to clear up the marker.

**Comment by egamma** [comment]
This is the expected behaviour.

>But I would like to know a list of all my errors through the project. So I defined a task to run  eslint  through the project.

This is the right thing to do and we recommend to do this using a task runner like gulp or grunt.

>Now I open an error and fixes it, but the marker is not cleared. 
If you want this behaviour then you should configure a `watch` task using your task runner. When you do this, then I recommended to configure running eslint with the --cache command line argument.
http://eslint.org/docs/user-guide/command-line-interface. In this way eslint is only run on files that have changed.

@dbaeumer we should document how to optimally configure eslint for a js project.

**Comment by daiheitan** [comment]
Thanks for the quick reply. I will try `watch`

**Comment by dbaeumer** [comment]
I looked into this and there is some misalignment with problem matchers defined in VSCode and extensions reporting errors. So I suggest to do the following:

- problem matchers that match eslint problems set the owner to eslint.
- Same for the eslint extension.

@egamma: this will make a much nicer expierence for eslint. We should do the same for jscs, tslint, jshint.

**Comment by egamma** [comment]
@dbaeumer fully agreed and I'm setting the owner inside vscode-tslint. What I don't do is to set the owner on the problem matcher.

**Comment by dbaeumer** [comment]
The owner for eslint problems is now correctly set to eslint.
