### ISSUE TITLE
sidebar explorer only shows errors on open files

### ISSUE THREAD

**Issue by maxxafari** [Microsoft/vscode-eslint#564]
When i select a project file inte the sidebar, the filname turns red and diplays the number of errors ie: +9 .

When i select a different file the file names return to yellow and the "+9" disappears. 

![eslint_vscode](https://user-images.githubusercontent.com/7019830/47481715-d350ff80-d834-11e8-9b53-5ba319cd16ac.gif)

```
{
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingQuotes": "never",
    "editor.codeLens": false,
    "workbench.startupEditor": "newUntitledFile",
    "explorer.confirmDelete": false,
    "window.zoomLevel": 0,
    "search.location": "panel",
    "search.smartCase": true,
    "terminal.external.osxExec": "ITerm.app",
    "editor.fontSize": 14,
    "eslint.alwaysShowStatus": true,
    "git.enableSmartCommit": true,
    "eslint.autoFixOnSave": true,
}
```

**Comment by dbaeumer** [comment]
This is actually following the VS Code error design guidelines. For linters the errors are only shown for files that are open in the editor. Errors are not shown for non visible files. 

The ESLint extension however offers a task which validate all JS files in the workspace and create errors for it. These errors stick until the next time the task is run of the file as been opened.

That support can be enabled by setting `eslint.provideLintTask` to true.

I will close the issue since this is expected VS Code behaviour. There is a bug though with restoring linter problems correctly in VS Code which will be addressed in the next release.
