### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ferisjuan** [Microsoft/vscode-eslint#620]
- Issue Type: `Performance`
- Extension Name: `vscode-eslint`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 4.19.16-1-MANJARO`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/xxx/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt` :warning:
[dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-eslint/files/2848461/dbaeumer.vscode-eslint-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by dbaeumer** [comment]
@jrieken I looked at the CPU profile and there is nothing specific from the ESLint extension in the profile. Any hint for what to look at? What might be special with ESLint is that it is activated eagerly since it depends on user configuration which file types it lints. I manually profiled the activate method and there is nothing special with it.

**Comment by jrieken** [comment]
Does it look like that: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading? Iff so then it's code loading.

**Comment by dbaeumer** [comment]
Closing. Version 1.8.1 ships web packed.
