### ISSUE TITLE
ESLint is not validating any files yet.

### ISSUE THREAD

**Issue by xerosanyam** [Microsoft/vscode-eslint#628]
Still happening in VSCode version 1.30.2, version of ESLint - 1.8.0

**Comment by dbaeumer** [comment]
@xerosanyam this works for me. Can you provide me with a GitHub repository I can clone that demos what you are seeing. Do you have eslint installed (`npm install eslint`)?

**Comment by joshunger** [comment]
I'm seeing the same issue @dbaeumer @xerosanyam 

Extension version: 1.8.0
VS Code version: Code - Insiders 1.32.0-insider (11416de365a1e96302e171c9eebc2547872ac230, 2019-02-23T08:16:36.706Z)
OS version: Darwin x64 18.2.0

```
$ which eslint
/Users/junger/.config/yarn/global/node_modules/.bin/eslint
```

**Comment by joshunger** [comment]
I had accidentally executed **ESLint: Disabled ESLint**. Executing **ESLint: Enable ESLint** fixed the issue. It might be helpful to update the text of this error message?

**Comment by dbaeumer** [comment]
@joshunger will look into it. Best would be to print some info about which workspace folders are disabled.

**Comment by shanemgrey** [comment]
> I had accidentally executed **ESLint: Disabled ESLint**. Executing **ESLint: Enable ESLint** fixed the issue.
> 
> So the steps to reproduce this issue are -
> 
> 1. Shift + Command + P and select **ESLint: Disabled ESLint**
> 2. Close vscode
> 3. Shift + Command + P and select **ESLint: Show Output Channel**
> 
> ![image](https://user-images.githubusercontent.com/2301847/53289296-9862c800-3751-11e9-90f7-17be732acdbb.png)
> 
> Is there a way to fix this error message?

Having the same problem today, I'm fairly sure I didn't disable EsLint at any point, 

But disabling and enabling it for the workspace did restore the AutoFixOnSave functionality I had working before.  Simply enabling it may have worked, but I first selected disable under the "Did you turn it off and back on?" rule of fixing things.

Thanks for the hint.

Uninstalling and reinstalling eslint did not fix the issue for me.

**Comment by daaru00** [comment]
Same issue, can someone provide more info about this error? The message "ESLint is not validating any files yet." does not mean nothing for me.

eslint is installed, configuration file is generate by `node_modules/.bin/eslint --init`, eslint is enabled inside project.. something else is required?

**Comment by daaru00** [comment]
After a lot of try I figure out what the problem is, you need to specify inside the vscode configuration the `eslint.validate` with file type that you want to lint. For example, in a Vue project you have to specify:
```
    "eslint.autoFixOnSave": true,
    "eslint.validate": [
        {
            "language": "vue",
            "autoFix": true
        },
        {
            "language": "html",
            "autoFix": true
        },
        {
            "language": "javascript",
            "autoFix": true
        }
    ]
```

Then, this is the really strange thing, nothing happens, will still not work, you have to disable and re-enable the linter with command `ESlint: Disable ESLint` and  `ESlint: Enable ESLint`, finally it start works!

So, the real issues are two:

1) the dummy error message that create a lot of confusion and does not provide any kind of information.. please, please, PLEASE, change it to something like "File type not configured, edit eslint.validate configuration" or "Check eslint.validate configuration to lint this file".

2) configuration changes are not applied and need a file open/close and/or enable and disable linter feature.

These two issues combined together make people crazy searching for the cause of this "non functioning behavior".

**Comment by dbaeumer** [comment]
I changed the message to:

<img width="340" alt="capture" src="https://user-images.githubusercontent.com/1931590/53940951-31c99c80-40b7-11e9-9f2b-d6fe8fb74155.png">


However I can't reproduce the lack of applying configuration changes. This works for me.

**Comment by daaru00** [comment]
>However I can't reproduce the lack of applying configuration changes.

@dbaeumer have you tried this?
1) remove the module
2) open a couple of files in a project environment
3) re-install the module
4) try to configure and run linter for that opened files

seems related to current open documents, I think.

**Comment by alexlouden** [comment]
I added `"eslint.trace.server": "messages"` to my user settings, then checked the Output of ESLint and got the following message:

> The language client requires VS Code version ^1.31 but received version 1.30.2

I tried to update, and discovered that VS code was running out of my downloads folder, so it couldn't update 🤦‍♂️ (see [issue](https://github.com/Microsoft/vscode/issues/7426)). I moved it to Applications, updated, and now ESLint is working again! Hope this helps someone else 😃

**Comment by dbaeumer** [comment]
@daaru00 the extension doesn't support hot install of the eslint npm package right now. I created https://github.com/Microsoft/vscode-eslint/issues/643.

**Comment by dbaeumer** [comment]
@alexlouden release a new version that addresses the version mismatch.

**Comment by dbaeumer** [comment]
Releases 1.8.2 which containes the improved error message

**Comment by mkp7** [comment]
Possible ways of reproducing the issue are to open a new window and then "open folder" or "add workspace folder" to it.

I remember opening a new window for a separate project, it was working with the previous workspace/window but not with the new window. Since then it isn't working with any folder/workspace.

All the folders I tested with had `eslint --init` done.

**Comment by AdriaRios** [comment]
Any update guys?
