### ISSUE TITLE
Doesn't work properly without jsconfig.json

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode-eslint#65]
If I read the documentation correctly, it says that without the jsconfig.json, each file is considered an *island*. But shouldn't each of them be properly linted by this plugin? Also, the eslint is already at the project root, so it shouldn't be because of that.

Right now, for the exact same project, this is what vscode gives me:
![vscode](https://cloud.githubusercontent.com/assets/760112/14486594/6a8931c6-017b-11e6-8732-44b87b65d9b8.png)

And this is the code, opened in atom:
![atom](https://cloud.githubusercontent.com/assets/760112/14486593/6a597c42-017b-11e6-8249-2ffe6dd5476b.png)

**Comment by egamma** [comment]
>If I read the documentation correctly, it says that without the jsconfig.json, each file is considered an island. 

Each file is considered an island for the VS Code JS language service. ESLint is not aware of the jsconfig.json and lints each file individually as an island.

The error message you see above is not from `eslint` but from the JS Language Service, it is prefixed with `[js]` if it would come from eslint then it would be prefixed with `[eslint]`. 

The error message shows up since the VS Code JS language service doesn't support the ES8 Rest/Spread operator for Objects. If you want to use the ES8 features then the recommendation is to disable the warnings from the VS Code JS language service by setting `javascript.validate.enable: false`.

If you have ideas how to make this more clear in the documentation then I'd appreciate an issue against the doc https://github.com/Microsoft/vscode-docs/issues/new.

Closing this issue since the behaviour above is as expected.

**Comment by kumarharsh** [comment]
ES....8? Wow, it's moving fast...

So, just to be clear, `javascript.validate.enable` will **disable** everything vscode does?

Because reading [these lines](https://github.com/Microsoft/vscode-docs/blob/391686213cb7d14d4cfe45b0287abd2dd461a303/docs/languages/javascript.md#disable-syntax-validation-when-using-es7-constructs) doesn't make it clear whether they should be made *true* or *false*
> Some users want to use syntax constructs like the proposed ES7 Object Rest/Spread Properties. However, these are currently not supported by VS Code's JavaScript support and are flagged as errors. For users who still want to use these ES7 features, we have **revived** the javascript.validate.enable setting

**Comment by dbaeumer** [comment]
@kumarharsh yes setting it to false disables VSCode's internal JS validation.

**Comment by egamma** [comment]
>Because reading these lines doesn't make it clear whether they should be made true or false

@kumarharsh thanks for pointing this out. I've updated the documentation.
