### ISSUE TITLE
VCS - JavaScript Space Errors

### ISSUE THREAD

**Issue by geekysmurf123** [Microsoft/vscode-eslint#652]
Hi.  Great project!  I am having an issue while using this in Visual Code Studio.  In my JavaScript files I am getting the red squiggly errors on all of my spaces/whitespaces.

I have identified that it is this extension by turning it off and then this issue goes away.
I checked all of the settings for this extension and nothing seems to take it away.

I checked online and there is no answer to this that I can find.  Can you tell me how to fix this?  Is there a setting that I am missing?

Thank you for your help!

**Comment by dbaeumer** [comment]
@geekysmurf123 this is very likely caused by the setting for ESLint itself (e.g. the settings maintained in the `.eslintrc` file). To verify this can you run eslint from a terminal and see which errors are reported. You can also use the  eslint `--print-config` option to see which settings eslint itself uses to validate a file.

I that all doesn't help can you provide me with a GitHub repository I can clone that demos what you are seeing.
