### ISSUE TITLE
race condition with validate onType and autoFixOnSave

### ISSUE THREAD

**Issue by Bkucera** [microsoft/vscode-eslint#687]
if validate is set to `onType`(default), there is a race condition where you make an edit and save before eslint has finished parsing, so no errors are detected in the handler for `autoFixOnSave`

This usually only happens with large files, but could be as simple to fix as checking if linting is currently happening, and waiting for it to finish before calculating file edits

**Comment by dbaeumer** [comment]
I think this is a different problem. There is a time budget limitation in VS Code for computing fixes on save. This is to avoid that extensions can block a save. The budget is fairly small (200ms) which might not be enough for large files. What the eslint extension should change is to let the user know when this happens to avoid confusion.

Implementation wise this has to happen on the client side since ESLint on the server side is running sync.

**Comment by dbaeumer** [comment]
Actually this got addressed by VS Code itself. They time budget is configurable and they show a notification informing the user about the situation.
