### ISSUE TITLE
[feature request] export a formatter to vs-code

### ISSUE THREAD

**Issue by zzzgit** [microsoft/vscode-eslint#689]
I want to use `eslint --fix` to format the file I am modifying. 
However, I don't want to type the command in terminal. 
Can you please export a formatter into vs-code for me to set it in `setting.json` as `editor.defaultFormatter: 'microsoft.prettier-vscode'`?

**Comment by dbaeumer** [comment]
Two options:

- enable autofix on save
- run autofix by command in VS Code itself using `Ctrl+Shift+P` > `ESLint: Fix all autofixable Problems`

Is there anything else you thing should be provided ?

**Comment by huw** [comment]
Hey @dbaeumer — I'm curious why this package overrides the save handler in VS Code instead of providing a formatter according to VS Code's specs. Is there some kind of extra behaviour required?

It would be neater (but obviously not critical) if we could select "ESLint Fix" as a formatter. Is there a possibility that having `eslint.autoFixOnSave` enabled while another formatter is specified on a file would cause conflicts?

**Comment by dbaeumer** [comment]
ESLint autfix is not a formatter. A formatter usually touched white space where are fix really changes your code. This is why this is implemented on save.
