### ISSUE TITLE
Allow omitting specific rules from fix

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/vscode-eslint#719]
I am aware #208 was already closed, however since then a specific API for filtering rules from being fixed was added to `CLIEngine` https://eslint.org/docs/developer-guide/nodejs-api#cliengine .

One of the pain points with the solution in #208 is that the `no-autofix` plugin requires adding it into every project specifically and only supports the builtin rules.

I'd like to propose again supporting an `eslint.rulesToDisableWhileFixing` option that takes a list of options. The `vscode-eslint` could then use this list like so:

```js
newOptions.fix = function({ ruleId }) {
  if (!pluginOptions.rulesToDisableWhileFixing) {
    return true;
  }
  return !pluginOptions.rulesToDisableWhileFixing.includes(ruleId);
}
```

**Comment by Jamesernator** [comment]
Alternatively as an event more flexible option it might be a possibility to treat `eslint.options.fix` as a function body if it happens to be a string e.g.:

```js
const fix = `typeof newOptions.fix === 'string' ? new Function('rule', newOptions.fix) : newOptions.fix;
```

**Comment by revelt** [comment]
PS. Atom has it already so VSCode should be able to implement it as well:

<img width="738" alt="atom_eslint" src="https://user-images.githubusercontent.com/8344688/62294512-ff07b280-b462-11e9-9c42-181afa97aba5.png">
—https://atom.io/packages/linter-eslint

**Comment by dbaeumer** [comment]
Good PR opportunity. 

However I am against `eval` since this will result in a security problem.

**Comment by revelt** [comment]
to add 2p., it's essential that we skip rules **on code editor level only**. When I upload the code to the CI (GitLab's or whatever), I do want the code to be fixed.

In practice, while developing, I want to exclude ESLint rules that catch `t.only()` isolated unit tests from auto-fixing. Otherwise, when I save, `.only` would get removed and unit test isolation would not work at all. But on CI release builds, I do want the autofix — if `t.only()` spills into production suddenly only one unit test will be checked, instead of the whole test suite. Bugs might pass through into production release.

It's very important to be able to disable autofixing at VSCode level only, not on `.eslint.rc` or anywhere where "normal", CI-driven ESLint would understand.

PS. Until it's implemented I can't use VSCode...

**Comment by branflaker** [comment]
Another idea for a possible implementation.  Instead of specifying specific rules to disable for autofixing, how about specifying a path to a separate config when autofixing?  You get a lot more control over how you want your autofixes applied then (more than just disabling specific rules).

**Comment by dbaeumer** [comment]
The next version (2.2.x) will contain a setting to customize the rules executed on save / fix. (e.g. eslint.codeActionsOnSave.rules)
