### ISSUE TITLE
vscode-eslint is not seeing NODE_ENV variable

### ISSUE THREAD

**Issue by Kostanos** [microsoft/vscode-eslint#741]
I'm straggling with NODE_ENV and vscode-eslint.

my **webpack.config.js** has multiples places where **process.env.NODE_ENV** is used.

NODE_ENV is set before vstudio called as `env NODE_ENV=development`

When you run `echo $NODE_ENV` in vstudio terminal, it prints **development**, but vscode-eslint always failed when reading my *webpack.config.js*

PS. when I run eslint from command line it works perfectly

Is there any specific attribute/parameter I'm missing in eslint configuration to fix this?

I checked 3 related issues (already closed, and I can't comment there) related to NODE_ENV and eslint, but didn't found the solution for my issue.

**Comment by dbaeumer** [comment]
Seeing it in the terminal doesn't necessarily mean that the variable is present in VS Code itself since the terminal launches it's own processes. Can you check the following

- Help -> Toggle Developer Tools
- in the developer tools console type `process.env.NODE_ENV`. 

What is the value?

If you are under Linux what might matter is how you start VS Code. Although we try to setup the shell environment when launching from a dock there might be a bug with it. So does the same happen if you start VS Code from a terminal where `NODE_ENV` is set

**Comment by Kostanos** [comment]
Thank you for support.
In Dev tools the `process.env.NODE_ENV` is undefined.

I found how to fix it.
I edited the - **/usr/share/applications/code.desktop** file
And added there: **env NODE_ENV=development**, to every Exec.

Now the file looks like:

```
$ cat /usr/share/applications/code.desktop 
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=env NODE_ENV=development /usr/share/code/code --unity-launch %F
Icon=com.visualstudio.code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.22

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=env NODE_ENV=development /usr/share/code/code --new-window %F
Icon=com.visualstudio.code
```

This resolves the issue. Thank you for help.

**Comment by dbaeumer** [comment]
@Kostanos great to hear you were able to solve the issue. Closing then.

**Comment by Skriptach** [comment]
I have faced this issue
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2157

My question is. How to set `NODE_ENV` for a `vscode-eslint` **only**? Preferably Workspace scoped
