### ISSUE TITLE
Support for .eslintrc.yml

### ISSUE THREAD

**Issue by kaelig** [Microsoft/vscode-eslint#76]
First of all, thanks to all the contributors for this extension!

YAML is now the recommended format for ESLint config files, is that something that this extension could support?

**Comment by dbaeumer** [comment]
@kaelig YAML is supported by the extension. Config can be defined in YAML and files are revalidated if the YAML file changes. What kind of support are you missing?

**Comment by kaelig** [comment]
My bad, I was under the impression that my configuration wasn't loaded and after reading the code it looked like yml wasn't supported at the time. Thank you

**Comment by zhaojinxiang** [comment]
@kaelig Could you tell me how to solve YAML support problem? Thanks.

**Comment by zhaojinxiang** [comment]
My bad, after uninstall es-beautifier, it works.

**Comment by Domiii** [comment]
Thanks for this great plugin!

Turns out, the issue is not with lack of support, it's lack of documentation.

The first thing a new developer sees is [this introductory text](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) which states, and I quote:

> On new folders you might also need to create a `.eslintrc` configuration file. You can do this by either using the VS Code command Create '`.eslintrc.json`' file or by running the eslint command in a terminal.

As you can see, it only talks about `.eslintrc` and `.eslintrc.json`. Maybe there can be a list or a link to reference to what kind of config formats are supported?
