### ISSUE TITLE
Multiple "Fix all" or "Auto fix" and one one always works, other doesn't!

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode-eslint#846]
<img width="1009" alt="Screen Shot 2019-12-18 at 12 55 18 PM" src="https://user-images.githubusercontent.com/4664695/71110745-e25fe300-2195-11ea-8ba7-0ec7339e4330.png">

Fix all works always and shows up as blue bulb icon,
Eslint: Fix ... doesn't and shows up as yellow icon.

I'd rather have only one option. Fix all.

**Comment by JarrodMFlesch** [comment]
What version are you using?

**Comment by techsin** [comment]
eslint 2.0.6
vscode 1.41.0
eslint 6.7.2
mac

**Comment by dbaeumer** [comment]
This is strange since I fixed this in 2.0.5. @techsin can you provide me with a GitHub repository I can clone that demos what you are seeing.

I agree that only having one command is preferable. The reason why I left the old one in is that users bound a key board short cut to it and it would be breaking for them if I remove the command.

**Comment by techsin** [comment]
https://github.com/techsin/eslint_double_auto_fix_vscode_reproducible_error/tree/master

**Comment by dbaeumer** [comment]
@techsin 

Fix All depends on VS Code's code action on save infrastructure. You need to enable this for ESLint first before that action works. Add

```
	"editor.codeActionsOnSave": {
		"source.fixAll.eslint": true
	}

```

**Comment by techsin** [comment]
I've that in my settings. It does make eslint Fix more consistent but fact remains eslint works and sometimes doesn't. But fix all always works.
