### ISSUE TITLE
eslint parserOption.project issue with typescript-eslint

### ISSUE THREAD

**Issue by armano2** [microsoft/vscode-eslint#872]
@dbaeumer i did some digging into issue #605 (i was trying to reproduce it from withing tests) and i can't reproduce this issue outside vscode.

This is somehow related to how vscode interacts with typescript (not sure where is a root cause).

## Context:
This issue at first seems to be related to https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/create-program/createWatchProgram.ts#L389-L406 and can be solved there by removing `break;` and triggering update to all directories that are registered, but this should no not needed. 

If i try to reproduce this issue in editor, i can do so by creating new vue file within src folder (ofc after any other file was already parsed)
https://github.com/armano2/typescript-eslint-1394 

But i'm unable to reproduce this issue from within tests or in other editors like Intellij Idea and atom.

Difference between vscode and other use cases is that somehow in vscode we are getting more roots that are defined in `folderWatchCallbackTrackingMap`

### folderWatchCallbackTrackingMap in tests

```
- c:\......\temp\tmp-25120kreh3kxu0pak\node_modules\@types
- c:\......\temp\tmp-25120kreh3kxu0pak
```

### folderWatchCallbackTrackingMap in vscode

```
- d:\projects\eslint-typescript-sandbox\node_modules
- d:\projects\eslint-typescript-sandbox\src
- d:\projects\eslint-typescript-sandbox\node_modules\@types
- d:\projects\eslint-typescript-sandbox
```

## Question
I understand that `vscode-eslint` is not doing anything "weird" to eslint or typescript, but do you know is there is anywhere (within vscode or vscode-eslint) code that can cause this weird behavior?

## How to reproduce
1. clone https://github.com/armano2/typescript-eslint-1394 
2. open it in vscode
3. open any file in src folder
4 create any vue file

## issue at typescript-eslint:
- https://github.com/typescript-eslint/typescript-eslint/issues/1303

**Comment by dbaeumer** [comment]
@armano2 the `vscode-eslint` extension doesn't do any file IO itself except for `existsSync` test which shouldn't trigger any file IO events. Which of these events are causing problems for you. IMO the one in `d:\projects\eslint-typescript-sandbox\src` is correct and the one in `d:\projects\eslint-typescript-sandbox` as well since a child changed. The ones that look strange to me are the one in `node_modules` ?

**Comment by armano2** [comment]
it's possible that this is vscode "thing" than, i managed to patch this out by allowing to update folders recursively, i still like to know why it's happening but for consumers it should work after next release.

**Comment by dbaeumer** [comment]
From our experience dealing with file events can be very tricky since it depends highly on the tool doing the file IO. For example saving a file might create a temp file which is then swapped with the original file to ensure consistency. I will check if VS Code does something special on `create` which triggers this.

So being defensive on your end is the right thing to do.

I am still not sure why these events cause problems. A change event in general doesn't necessarily mean that the content has changed. Attribute changes trigger that as well.

**Comment by dbaeumer** [comment]
@armano2 please ping if you think there is something I can help with.

**Comment by armano2** [comment]
@dbaeumer i patched this issue on ts-estree side, than it should no longer cause issues for ppl, than it can be considered closed as for now i'm unable to determine why/how this weird behavior is created, if i find something more i will create appropriate ticket 🐱
