### ISSUE TITLE
Hanging (100% CPU indefinitely) Code Helper process (with repro)

### ISSUE THREAD

**Issue by coreyward** [microsoft/vscode-eslint#887]
When using the latest version of vscode-eslint with prettier configured, opening a large minified JavaScript file results in a VSCode “Code Helper (Renderer)” process consuming 100% CPU indefinitely.

Here's a minimal reproduction: https://github.com/coreyward/vscode-eslint-hanging-demo

And lest this be attributed to Prettier, it should be known that running prettier directly on this file on the same machine takes ~1.9–2.3s fairly consistently.

**Comment by dbaeumer** [comment]
I can reproduce this but the CPU cycles are spent in a diff function called by the prettier plugin:

![capture](https://user-images.githubusercontent.com/1931590/73646303-73711780-4679-11ea-83d2-dfb403124f03.png)

**Comment by dbaeumer** [comment]
Same happens to me when validating the file using eslint in the terminal:

![capture](https://user-images.githubusercontent.com/1931590/73646454-c4810b80-4679-11ea-97b9-f753eeed4fd3.png)

Command used is: `./node_modules/.bin/eslint highcharts-editor.complete.min.js`

@coreyward can you please report the issue against `eslint-plugin-prettier` since there is little I can do to fix this.
